### ISSUE TITLE
vulkaninfo should load all instance-level extensions

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-Tools#100]
Due to vulkan 3.33 "Extension Dependencies":

> Any device extension that has an instance extension dependency that is not enabled by vkCreateInstance is considered to be unsupported, hence it must not be returned by vkEnumerateDeviceExtensionProperties for any VkPhysicalDevice child of the instance.

Now, the goal of vulkaninfo is obviously to list all available device-level extensions. However, because of this paragraph in the vulkan spec, any device-level extension that depends on missing instance-level extensions will be censored from the output of vulkaninfo.

I propose changing vulkaninfo in such a way that it loads all available instance-level extensions. (Not sure if we need to be careful on systems with multiple ICDs? Is it possible to load a VkInstance extension that is compatible with one VkPhysicalDevice but not another?)

**Comment by krOoze** [comment]
Makes sense. It is probably also desirable to report all the added extension caps, props, and features.

Question is how to do it. It is probably safe to enable extensions that were promoted to 1.1.
There's one extension that is invalid to enable ("nega-dependency"). What would be better:

a) enable all supported extensions reported by enumerate, and hope no new nega-dependencies arrive (or this app would stop working)

b) enable only extensions we know at the moment, and this app would need to be updated with every new extension.

> Is it possible to load a VkInstance extension that is compatible with one VkPhysicalDevice but not another?

That should be so. Loader censors instance extensions it itself does not know. And Loader should emulate instance extension for the ICDs that do not know it.

**Comment by haasn** [comment]
Can you give an example of such a nega-dependency? If they're added only infrequently, a whitelist alone seems like a bad idea.

And presumably, if we request a new extension which conflicts with other enabled extensions, instance creation would fail? If so, there's a third option: c) Have a list of known bad and known good extensions. Enable everything except the known bad list by default. If that fails, enable only the known good extensions. This might offer some sort of middle ground.

**Comment by krOoze** [comment]
@haasn  Only `VK_AMD_negative_viewport_height` so far I think, but I see it is a Device extension, so not a problem here...

The creation would not "fail". It would be an undefined behaviour (assuming it is done same as `VK_AMD_negative_viewport_height`

**Comment by haasn** [comment]
> The creation would not "fail". It would be an undefined behaviour

This, unfortunately, would lock us into a whitelist approach unless we're comfortable accepting undefined behavior in `vulkaninfo`, the answer to which is probably "no".

However,

> @haasn Only VK_AMD_negative_viewport_height so far I think, but I see it is a Device extension, so not a problem here...

That makes a lot more sense. Given the scope/function of instance-level extensions, and the fact that the loader is apparently supposed to be capable of emulating them, I have a hard time seeing instance-level extensions conflict with other instance-level extensions even in the future. So in light of this, I don't think we need to worry about it until it happens.
