### ISSUE TITLE
BadMatch on X_CreateWindow running on xrdp on Rocky 9

### ISSUE THREAD

**Issue by rp42** [KhronosGroup/Vulkan-Tools#1041]
This is on a VM with an NVIDIA Titan RTX GPU passed through. The `vulkaninfo` command works fine on the console, but on an `xrdp` session it fails:

```
$ vulkaninfo
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  7
  Current serial number in output stream:  8
```

We had a simlar issue in one of our applications and traced it to the fact that the default X11 visual is not the first one in the list returned:

[xrdp_xdpyinfo.txt](https://github.com/user-attachments/files/17457456/xrdp_xdpyinfo.txt)

In our app I was able to work around this by searching the list of visuals for the visual returned by DefaultVisual(). Would that be a suitable fix in `vulkaninfo`?

**Comment by charles-lunarg** [comment]
Yes, that would be a suitable solution to the problem. I'll happily review & accept a PR which fixes the issue.

**Comment by charles-lunarg** [comment]
Closing as completed.
