### ISSUE TITLE
FindVulkanHeaders.cmake might not set VulkanRegistry_DIR (macOS)

### ISSUE THREAD

**Issue by DzmitrySafin** [KhronosGroup/Vulkan-Tools#108]
I provide VULKAN_HEADERS_INSTALL_DIR and VULKAN_LOADER_INSTALL_DIR paths. I want to use those dependencies in the repositories I cloned/built instead of duplicating them with update_deps.py. In this case problem appears in this call (cmake/FindVulkanHeaders.cmake):
find_path(VulkanHeaders_INCLUDE_DIR
    NAMES vulkan/vulkan.h
    HINTS
        ${VULKAN_HEADERS_INSTALL_DIR}/include
        "$ENV{VULKAN_HEADERS_INSTALL_DIR}/include"
        "$ENV{VULKAN_SDK}/include")
This function uses global VULKAN_LOADER_INSTALL_DIR to set VulkanHeaders_INCLUDE_DIR value. It is possible because VulcanLoader has vulkan.framework package, so find_path ignores hints and VulkanHeaders_INCLUDE_DIR will point to "..../loader/vulkan.framework/Headers".
Obviously, there is no "share/vulkan/registry" folder in the vulkan.framework, so VulkanRegistry_DIR will be not defined.
In order to make find_path use hints (it should search VULKAN_HEADERS_INSTALL_DIR for VulkanHeaders), I added NO_DEFAULT_PATH parameter, like this:
find_path(VulkanHeaders_INCLUDE_DIR
    NAMES vulkan/vulkan.h
    HINTS
        ${VULKAN_HEADERS_INSTALL_DIR}/include
        "$ENV{VULKAN_HEADERS_INSTALL_DIR}/include"
        "$ENV{VULKAN_SDK}/include"
    NO_DEFAULT_PATH)
After that cmake worked fine with all the provided parameters (VULKAN_HEADERS_INSTALL_DIR, VULKAN_LOADER_INSTALL_DIR, MOLTENVK_REPO_ROOT etc).

Would it be an appropriate fix?

**Comment by jeremyk-lunarg** [comment]
After testing it would seem this problem has been resolved.
Feel free to reopen the issue if you still see the problem occurring.
