### ISSUE TITLE
Snap Package Support (Feature Request) 

### ISSUE THREAD

**Issue by mikeroyal** [KhronosGroup/Vulkan-Tools#117]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by jeremy-lunarg** [comment]
Sounds good to me. :+1:  Please feel free to submit a PR.

**Comment by jeremyk-lunarg** [comment]
@mikeroyal since this is a feature suggestion and you have already said you will be working on it, I will close this issue.

Feel free to reopen it if necessary.
