### ISSUE TITLE
vkcube: By which mechanism is the depth buffer synchronized

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Tools#122]
May I ask by which mechanism is the depth buffer synchronized in the `vkcube` demo?
This seems to be the source of many tutorials, but I suspect they just copy-paste this aspect without knowing why it works...

First use in frame seem to be the `loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR` (i.e. `VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT`), and last use the `storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE` (i.e. `VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT`).

The default `FRAME_LAG` is `2`, so it means there may purely theoretically be an overlap. I.e. fence wait is on an older frame, and not the immediately previous one.

There seem to be no subpass dependencies (except the implicitly defined ones).
The implicit renderpass external dependencies should do half the jorb. I.e. it  would make the depth buffer successfully "available from", but **not** "visible to" the ` loadOp` of the next frame.
Similarly, the implicit renderpass external dependencies of the next frame would make it "visible to", but not "available from" the previous frame. An execution dependency is missing between the two to make it work.

And there seem to be no pipeline barriers.

There is a semaphore signal on the batch, but only `vkQueuePresent` waits on it, which implies nothing about the state of the resource to the next frame. That is so because based on spec it does not cover subsequent submissions:

> Also, in the case of `vkQueueSubmit`, the second synchronization scope additionally includes all commands that occur later in submission order.

There is a semaphore wait on the batch. But the semaphore is from `vkAcquireNextImageKHR`, which does not imply much about the state of the draw of the previous frame. And the `pWaitDstStageMask` is `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT` which does not match the depth buffer `loadOp` anyway.

I think the only way this would work is if there was some implicit relation of `vkQueuePresent` and `vkAcquireNextImageKHR`, that I cannot support from spec. (Or some other obscure mechanism from spec, which I missed, that is outside the realm of the conventional synchronization model).

**Comment by Tony-LunarG** [comment]
Fixed with #200
