### ISSUE TITLE
vkvia stops running if driver json not present

### ISSUE THREAD

**Issue by davidlunarg** [KhronosGroup/Vulkan-Tools#127]
I have a laptop with both Intel and nVidia graphics. I wanted to used Intel graphics, so I renamed C:\Windows\System32\nv-vk64.json to nv-vk64.jsonHIDE.

I ran via. It  seems to exit prematurely. The output file has an error msg that it can't read the nVidia json file (would be expected), I don't see vkcube get run, and less information is in the html file.

It seems that via should have still run to the end in spite of the missing json file, especially given that vulkaninfo does run successfully and identify the output device as Intel graphics.

**Comment by MarkY-LunarG** [comment]
Closing because:
1. This is on the wrong repo (KhronosGroup/Vulkan-Tools instead of LunarG/VulkanTools)
2. I have a PR in LunarG/VulkanTools to resolve this [LunarG/VulkanTools #714](https://github.com/LunarG/VulkanTools/pull/714)
