### ISSUE TITLE
rename winrt directory

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/Vulkan-Tools#134]
The directory `winrt/` contains the Windows Runtime Installer.

The directory name is confusing. `WinRT` is a thing on modern Windows.  It is a modern replacement for what's commonly referred to as `win32`.  The use of the `winrt` directory name creates confusion.  My first assumption was that it is an attempt to provide access to Vulkan from the WinRT API.

Suggest renaming the directory to something like `windows-runtime-installer`.  This name would be accurate and obvious. It's even the same text as the "title" within winrt/README.md.

**Comment by jeremyk-lunarg** [comment]
Fixed by merge of PR #295.
