### ISSUE TITLE
support vulkaninfo on Android

### ISSUE THREAD

**Issue by renjiayuan1314** [KhronosGroup/Vulkan-Tools#138]
Hi,

When we building the Vulkan-Tools for Android, we can get vkcube apk, but there is no vulkaninfo apk. https://github.com/KhronosGroup/Vulkan-Tools/blob/master/build-android/build_all.sh

From the code, seems we are going to support Android in the future. https://github.com/KhronosGroup/Vulkan-Tools/blob/master/vulkaninfo/vulkaninfo.c#L165

Are there any details about that? When do we expect to see vulkaninfo on Android?

Thanks, 
Jiayuan.

**Comment by cnorthrop** [comment]
I don't recall it ever working for Android.  That code might be placeholder.  At most, it would have been run as a native executable, not an APK.

We do have something in the Android tree ([vkjson](https://android.googlesource.com/platform/frameworks/native/+/master/vulkan/vkjson/)).  To use it, you can run the following command, which I believe gives info similar to `vulkaninfo`:

```
adb shell cmd gpu vkjson
```

**Comment by cnorthrop** [comment]
To clarify, there is no planned work for vulkaninfo for Android.

**Comment by renjiayuan1314** [comment]
Thanks, Cody for the clarification.

**Comment by HackHarry** [comment]
@cnorthrop Hi, I find that running `adb shell cmd gpu vkjson` in some Low-end phone will cause the phone to restart. I guess it's because too much info need to get when run this script.
I just want to get the vulkan apiVersion with adb. Could you have some suggestion about it?

**Comment by jeremyk-lunarg** [comment]
@HackHarry this repo is specifically for Vulkan-Tools repo issues.
If you have a question about Vulkan on Android, I would recommend you ask on the Android developer forums or Reddit.
