### ISSUE TITLE
Vulkan has memory leak on arch linux

### ISSUE THREAD

**Issue by Makogan** [KhronosGroup/Vulkan-Tools#164]
Valgrind reports memory leaks when using vulkan in arch linux:

https://gist.github.com/Makogan/610ca9901eacdc72eecb72bcf0aa153c

Related reddit thread:
https://www.reddit.com/r/vulkan/comments/b1wt4y/vulkan_has_massive_memory_leaks/

**Comment by xorz57** [comment]
In case Vulkan Implementation has custom allocators, Valgrind can't monitor those I think. So you will always get false positives.

**Comment by jeremyk-lunarg** [comment]
A similar issue was reported in the [Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader) repo [here](https://github.com/KhronosGroup/Vulkan-Loader/issues/256).
In that issue an explanation was give as to why you might see some memory leaks reported by Valgrind.
