### ISSUE TITLE
vulkaninfo.c:630: failed with VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by xorz57** [KhronosGroup/Vulkan-Tools#175]
I recently installed `VulkanSDK` version 1.1.101.0 and after restarting my PC I decided to open `vulkaninfo` and it gave me an error.

## Hardware
- NVIDIA GTX 1070

## Software
- Vulkan SDK 1.1.101.0
- NVIDIA CUDA 10.1
- NVIDIA Driver 419.67
- Windows 10 Pro

## Screenshots
![image](https://user-images.githubusercontent.com/1548352/56041117-a4760980-5d40-11e9-89bc-73a80e64d061.png)

For the record, I installed the following executable

![image](https://user-images.githubusercontent.com/1548352/56046692-7b5b7600-5d4c-11e9-9286-b99c485d9d0c.png)

**Comment by xorz57** [comment]
Do I also need to install `VulkanRT`?

**Comment by architector1324** [comment]
Hello! I have similar problems with `vulkaninfo` app
## Hardware
- AMD Radeon R5 / R7
## Software
- Arch Linux (4.19.33-1-lts)
- `vulkan-radeon`, `vulkan-tools`
- `mesa` driver

## Screenshot
![Снимок экрана от 2019-04-12 18-00-53](https://user-images.githubusercontent.com/43575092/56046906-f7ee5480-5d4c-11e9-8f96-25e6fcd631e3.png)

**Comment by pdaniell-nv** [comment]
> Do I also need to install `VulkanRT`?

You shouldn't need to. I'm curious, what happens if you reinstall the display driver.

**Comment by xorz57** [comment]
@pdaniell-nv I will give it a try.

**Comment by xorz57** [comment]
@pdaniell-nv Thank you so much! Installing a driver update worked for me (I guess it counts as reinstalling drivers). Have a nice day!

![image](https://user-images.githubusercontent.com/1548352/56052845-25da9580-5d5b-11e9-8e16-cd70e5125f7b.png)

**Comment by pdaniell-nv** [comment]
Thanks for doing that experiment. This might still be a real issue because installing a new SDK shouldn't cause Vulkan to stop working. In any case, I'm glad you're unblocked now.

**Comment by KarenGhavam-lunarG** [comment]
I would like to reopen this issue. Installing a new SDK shouldn't cause Vulkan to stop working and we need to understand why.

**Comment by xorz57** [comment]
Forgive me if I am wrong. I just installed a display driver update and only that. I didn't reinstall Vulkan SDK or previously installed an older version of Vulkan SDK and decided to install the new version.

**Comment by aradhyamathur** [comment]
@xorz57 which display driver version are you running now. I am running 418.56 and getting the same error.

**Comment by light307** [comment]
hey im trying to get vulkan regognised on rpc3 emulator ps3 it gives me same error as his do any know how to fix it? i think i have radeon driver vulkans drivers are not showing upp eatheir on r egistry editor https://prnt.sc/u6d1if

**Comment by light307** [comment]
how do u uppdate vulkan?

**Comment by charles-lunarg** [comment]
Update your drivers using the normal means, ie, go to the radeon website, download the driver, and install it.
The picture shown has nothing to do with the driver, and won't tell you anything about the driver install on your system.

**Comment by light307** [comment]
only have radeon  i dont have amd or nvidia :/

**Comment by light307** [comment]
i have probook6460b windows 10 64 bit :)

**Comment by light307** [comment]
wait it was intel R HD thats my only driver

**Comment by charles-lunarg** [comment]
This is not the place to get technical support for what is driver installation or system setup issues.

**Comment by light307** [comment]
ah okey i figured out how to uppdate but vulkan is not showing upp on computer? where my devices is? is there a special location its in? thnx for asnwer
