### ISSUE TITLE
vulkaninfo --html Presentable Surfaces section confusing

### ISSUE THREAD

**Issue by jeremyk-lunarg** [KhronosGroup/Vulkan-Tools#178]
The "Presentable Surfaces" section currently lists GPUs multiple times when listing multiple surface types.

Potential fix would be to list a "Surface Type" subsection under each GPU in the "Presentable Surfaces" section that would contain the properties and capabilities of each surface type.

**Comment by charles-lunarg** [comment]
Created PR #270 to fix this. 
It will look for all surfaces with identical properties and GPU's and list the surface types in an array.
