### ISSUE TITLE
vulkaninfo: Improve error reporting for common failures

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Tools#207]
We see a lot of:

```
Cannot create Vulkan instance.
C:\VulkanSDKBuild\workspace\Khronos-Tools\repo\vulkaninfo\vulkaninfo.c:921: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

It may be good to add some text such as "This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan."

I know that any detailed reporting here is more in the domain of Via, but perhaps this small hint will help users direct their attention to the most likely source of the problem.

**Comment by mark-lunarg** [comment]
Ah! It was unclear to me that "_this particular_ error message" referred to the vulkaninfo output, this is a fantastic idea.
