### ISSUE TITLE
vulkaninfo: Add support for vkGetPhysicalDeviceFeatures2KHR pNext extension queries

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Tools#218]
There are extension features and properties that are available through the pNext chain in calls to vkGetPhysicalDeviceFeatures2 that could be reported by vulkaninfo.  Specifically, I would like to see VkPhysicalDeviceDescriptorIndexingFeaturesEXT and VkPhysicalDeviceDescriptorIndexingPropertiesEXT, but there are probably others with other interests.

**Comment by mikew-lunarg** [comment]
There are pNext query structures added by extensions (e.g. portability_subset) to both Features2 and Properties2 that would be very useful to have reported.

**Comment by Tony-LunarG** [comment]
Actually, the support for the pNext chains is there, but doesn't have some of the more recent extensions

**Comment by charles-lunarg** [comment]
Which more recent extensions aren't included? Working on the backlog, and would appreciate more info.

**Comment by charles-lunarg** [comment]
The vulkaninfo refactor includes auto generative capability which find all physical device properties and features, so it should find all the most recent extensions from the headers.
