### ISSUE TITLE
cube.c demo_set_image_layout() image memory barrier does not set srcQueueFamilyIndex / dstQueueFamilyIndex

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/Vulkan-Tools#22]
"If image was created with a sharing mode of VK_SHARING_MODE_EXCLUSIVE and srcQueueFamilyIndex is not VK_QUEUE_FAMILY_IGNORED, it must be a valid queue family" ... Same with dstQueueFamilyIndex.

I don't see demo_set_image_layout() doing this.

In cube.cpp Demo::set_image_layout() sets these to 0, shouldn't that be graphics_queue instead?

**Comment by Tony-LunarG** [comment]
Fixed with PR #26
