### ISSUE TITLE
vulkaninfo: on MacOS vulkaninfo repeats Presentable Surface Formats

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Tools#227]
In section 'Presentable Surfaces' under subsection 'Formats' vulkaninfo claims there are 32 formats, but repeats the same 4. 

Presentable Surfaces:
=====================
GPU id       : 0 (Intel(R) Iris(TM) Plus Graphics 640)
Surface type : VK_MVK_macos_surface
Formats:		count = 32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32
	B8G8R8A8_UNORM
	B8G8R8A8_SRGB
	R16G16B16A16_SFLOAT
	A2R10G10B10_UNORM_PACK32

@cdavis5e informed us that: That's because, if you enable `VK_EXT_swapchain_colorspace`, MoltenVK now reports some of the color spaces defined therein. The other 28, then, are for each additional color space beyond `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR` that we support. But `vulkaninfo` does not print the color space for each enumerated format.

**Comment by jeremyk-lunarg** [comment]
Fixed with merge of PR #256
