### ISSUE TITLE
vulkaninfo: Report old drivers being dropped by the loader

### ISSUE THREAD

**Issue by lenny-lunarg** [KhronosGroup/Vulkan-Tools#247]
In today's SI meeting, we agreed on a change to loader behavior that will cause the loader to drop very old drivers when newer ones are present. The loader will log a message when ignoring old drivers so that applications can see what is happening. We we need to make sure that vulkaninfo is capable of reporting this warning.

At the very least, vulkaninfo will need to pass on this warning message so that someone who runs it can see the message. It may also be useful provide some sort of hint that this can be fixed by updating drivers. I'll post a link to the loader PR that intrudces this behavior once I open it (which should happen shortly).

**Comment by charles-lunarg** [comment]
Currently vulkaninfo uses debug_report and should return any loader messages that go through that channel. 
We will need to test this to make sure the messages get through but for now no changes need to be made as far as I can tell.

**Comment by krOoze** [comment]
@lenny-lunarg That is actually pretty weird behavior. Is this documented in [oaderAndLayerInterface.md](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md)?

**Comment by charles-lunarg** [comment]
Closing the issue as vulkaninfo uses the debug report callback in vkCreateInstance, which is where this error should be reported.

> @lenny-lunarg That is actually pretty weird behavior. Is this documented in [LoaderAndLayerInterface.md](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md)?

I don't think it is. But the document is long and easy to miss minor details like that.
