### ISSUE TITLE
cube: not explicitly handling vkAcquireNextImageKHR returning VK_ERROR_SURFACE_LOST_KHR

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-Tools#252]
I have been working on debugging a problem on ARM Mali/Android 9 with my swapchain handling code in my engine.  I had based some of my code off of the cube example, and had been somewhat led astray by this code here:

https://github.com/KhronosGroup/Vulkan-Tools/blob/5e453384b73751d471467b34bb3e4e19e1073b96/cube/cube.c#L1009

I'm not sure if it happens with the cube sample on ARM Mali, but at least in my own code there are cases where VK_ERROR_SURFACE_LOST_KHR is returned by vkAcquireNextImageKHR and handling that case is required.

Now, granted - the cube code will work, although it will assert.  I think it would be better though if it called out that as a case since this serves as example code on how to handle the swapchain (especially with it being referenced as the canonical example of how to use VK_GOOGLE_display_timing).

**Comment by Tony-LunarG** [comment]
Fixed via #259
