### ISSUE TITLE
Incompatible binary downloaded

### ISSUE THREAD

**Issue by mittorn** [KhronosGroup/Vulkan-Tools#254]
```
/bin/sh: ../../glslang/bin/glslangValidator: cannot execute binary file
```
Why do you download incompatible binaries?
Maybe better build from source if binary is not availiable?

**Comment by jeremyk-lunarg** [comment]
Please provide more context.
What are your system specs?
Where are you getting your glslangValidator from?
What are you trying to use your glslangValidator for?

**Comment by mittorn** [comment]
It is downloaded automaticly by cmake, it seems to be x86_64 linux binary

**Comment by karl-lunarg** [comment]
@mittorn The "glslang" section of the BUILD.md file in this repository explains what is going on here.  The file also tells you how to build from source if a binary is not available for your platform.

That being said, we should probably try to improve the cmake files to download the binary only if there is one available for the platform.

**Comment by jeremyk-lunarg** [comment]
@mittorn I will be closing this by EOD.
If you are still having problems feel free to comment or reopen the issue.
