### ISSUE TITLE
vulkaninfo ignores --show-formats for --html, --json

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Tools#283]
See https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/173#note_223404 found during SDK testing of 1.1.126

vulkaninfo always acts as though --show-formats was passed when either --html or --json is passed.  I didn't expect this behavior.
I prefer that vulkaninfo respect --show-formats in all cases.  It's acceptable that vulkaninfo always assumes --show-formats in --html and --json modes if this is clearly documented.

The original discussion mentioned that the option only makes sense for text, so always enabling show-formats for html & json made sense. The only change should be to update the documentation to reflect it.

**Comment by charles-lunarg** [comment]
Created PR #287 to address the lack of documentation.

**Comment by charles-lunarg** [comment]
PR is merged, closing issue.
