### ISSUE TITLE
 vulkaninfo has inconsistent output standards 

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Tools#284]
vulkaninfo sends output to stdout.
vulkaninfo --html sends output to the file vulkaninfo.html.
vulkaninfo --json sends output to stdout.
For consistency, either vulkaninfo should always send output to stdout, and rely on the user to redirect if necessary; or vulkaninfo --json should send output to the file vulkaninfo.json.  I prefer the former.

See issue https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/174#note_223405

From Charles: The original version of vulkaninfo did exactly this. I preserved the original behavior to ease the transistion. The exact format and defaults would need to be figured out, as preserving existing behavior is useful but not tantamount. The internal logic was designed for this use case in mind, so if and when it gets addressed, it will be very easy to do.

**Comment by mikew-lunarg** [comment]
+1 for all output going to stdout.

Running `vulkaninfo --html > myfile.html` produces an empty myfile.html.  Not what one would expect.

Should we be giving notice in this SDK of the intent to change the existing behavior?

**Comment by charles-lunarg** [comment]
Created PR #288 to address this issue.

From my understanding, we will need to put out a notice to anyone using the html version, but I think the uniformity and matching expectations is well worth it.

**Comment by charles-lunarg** [comment]
vulkaninfo now has an output format specifically for vkconfig. Unfortunately it required printing to a file as well, and makes it much harder to justify making the vulkaninfo html output print to std-out. As such I'm closing the issue.
