### ISSUE TITLE
vkcube: MacOS vkcube is squished

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Tools#285]
See SDK issue: https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/189

Is there code that can be put into vkcube to avoid this? Is this unique to Mac or happens on other platforms?

**Comment by mikew-lunarg** [comment]
The field of view is being computed from both the window's height and width, so if the window doesn't have a square aspect ratio, the view is squished.  

To preserve an aspect ratio, use either the height or width to compute the FOV, and use that single FOV for both horizontal and vertical.

**Comment by jeremyk-lunarg** [comment]
Fixed by PR #296
