### ISSUE TITLE
Building windows VulkanInfo (from VulkanTools repo) generates many warnings

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-Tools#298]
Could be it's already been fixed, but lots of 'size_t to init' warnings.

**Comment by charles-lunarg** [comment]
Went through with a fine toothed comb (and after enabling /W4) to make a PR #301 which should remove most of these warnings.

**Comment by charles-lunarg** [comment]
Just merged the PR, so I am closing the issue.
