### ISSUE TITLE
[CLOSED] Smoketest with validation spews errors on resize (NVIDIA, Linux)

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Tools#3]
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Friday Dec 09, 2016 at 22:57 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1250_

----

**Comment by karl-lunarg** [comment]
<a href="https://github.com/mark-lunarg"><img src="https://avatars2.githubusercontent.com/u/7252958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mark-lunarg](https://github.com/mark-lunarg) (MIGRATED)**
_Monday May 14, 2018 at 14:42 GMT_

----

This issue will be Migrated to the Vulkan-Tools repo.  Closing.

**Comment by krOoze** [comment]
smoketest was deleted. This can be closed?

**Comment by jeremyk-lunarg** [comment]
Closing this issue because Vulkan-Tools no longer contains smoketest.
