### ISSUE TITLE
vulkaninfo: MacOS Presentable Surfaces information mixup

### ISSUE THREAD

**Issue by jeremyk-lunarg** [KhronosGroup/Vulkan-Tools#311]
On MacOS, sometimes VK_MVK_macos_surface and VK_EXT_metal_surface output the same properties in vulkaninfo and other times output different properties.

**Comment by charles-lunarg** [comment]
@jeremyk-lunarg The #331 PR should of fixed this. Could you double check that the issue still occurs?
