### ISSUE TITLE
vulkaninfo "Presentable Surfaces" seem incorrect 

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-Tools#312]
On an **Ubuntu AMD** machine, `vulkaninfo` reports no presentable surfaces:
```
$ export DISPLAY=:0
$ vulkaninfo
...
Presentable Surfaces:
=====================

Groups:
=======
...
```
`vulkaninfo --html` gives the missing presentable surfaces - but seems to present each of the surfaces *twice*:
![image](https://user-images.githubusercontent.com/45772930/71123945-0d9bff80-21a1-11ea-84a0-9aa44963efa6.png)

**Comment by charles-lunarg** [comment]
This issue is fixed with PR #331 
Closing issue.
