### ISSUE TITLE
CMake create_symlink error happens on MacOS

### ISSUE THREAD

**Issue by bojie-liu** [KhronosGroup/Vulkan-Tools#340]
I followed the instructions in last section of BUILD.md and encountered the following compile error. My Vulkan SDK is: vulkansdk-macos-1.2.131.1. 

/Applications/CMake.app/Contents/bin/cmake -E create_symlink /Users/joshualiu/dev/source/git/Vulkan-Tools/icd/macos/VkICD_mock_icd.json Debug /Users/joshualiu/dev/source/git/Vulkan-Tools/build-xcode/icd/Debug/VkICD_mock_icd.json
CMake Error: cmake version 3.10.2
Usage: /Applications/CMake.app/Contents/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
......[more commands]
  time command [args...]    - run command and return elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
Available on UNIX only:
  create_symlink old new    - create a symbolic link new -> old

**make: *** [/Users/joshualiu/dev/source/git/Vulkan-Tools/build-xcode/icd/CMakeFiles/VkICD_mock_icd-json] Error 1
Command /bin/sh failed with exit code 2**

**Does the parameter "Debug" for create_symlink make sense here?** 
/Applications/CMake.app/Contents/bin/cmake -E create_symlink /Users/joshualiu/dev/source/git/Vulkan-Tools/icd/macos/VkICD_mock_icd.json **Debug** /Users/joshualiu/dev/source/git/Vulkan-Tools/build-xcode/icd/Debug/VkICD_mock_icd.json

I found that the source compile script is at icd/CMakeLists.txt. There is an extra $< CONFIG > when made for Xcode.
```
        if(CMAKE_GENERATOR MATCHES "^Xcode.*")
            add_custom_target(mk_icd_config_dir ALL
                              COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>)
            foreach(config_file ${ICD_JSON_FILES})
                add_custom_target(${config_file}-json ALL
                                  DEPENDS mk_icd_config_dir
                                  COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_CURRENT_SOURCE_DIR}/macos/${config_file}.json
                                          $<CONFIG> ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/${config_file}.json
                                  VERBATIM)
            endforeach(config_file)
        else()
            foreach(config_file ${ICD_JSON_FILES})
                add_custom_target(${config_file}-json ALL
                                  COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_CURRENT_SOURCE_DIR}/macos/${config_file}.json
                                          ${config_file}.json
                                  VERBATIM)
            endforeach(config_file)
        endif()
```

**Comment by jeremyk-lunarg** [comment]
While I'm looking into this, could you try building with update_deps.py and known_good.json?
Building the repo this way is described here:
https://github.com/KhronosGroup/Vulkan-Tools/blob/master/BUILD.md#building-dependent-repositories-with-known-good-revisions.

**Comment by jeremyk-lunarg** [comment]
I can't seem to reproduce the problem.
Has building the dependent repos with known-good helped you?

**Comment by jeremyk-lunarg** [comment]
@bojie-liu Is this problem still occurring for you?
If there is no update by midday tomorrow, I will assume the problem has been resolved and close the issue.
