### ISSUE TITLE
vulkaninfo tries to use X11 on Wayland

### ISSUE THREAD

**Issue by devurandom** [KhronosGroup/Vulkan-Tools#370]
I am trying to run vulkaninfo 1.2.135 on Sway WM 1.4:
```
# vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
error: XDG_RUNTIME_DIR not set in the environment.
No protocol specified
XCB failed to connect to the X server due to error:1.
ERROR at /tmp/portage/dev-util/vulkan-tools-1.2.135/work/Vulkan-Tools-1.2.135/vulkaninfo/vulkaninfo.h:805: AppCreateXcbSurface failed to establish connection
```

When I explicitly unset `$DISPLAY`, I get this:
```
# vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR at /tmp/portage/dev-util/vulkan-tools-1.2.135/work/Vulkan-Tools-1.2.135/vulkaninfo/vulkaninfo.h:990: 'DISPLAY' environment variable not set... skipping surface info
```

vulkan-tools were build with:
```
make -C /tmp/portage/dev-util/vulkan-tools-1.2.135/work/vulkan-tools-1.2.135_build-abi_x86_64.amd64/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH=ON -DBUILD_VULKANINFO=ON -DBUILD_CUBE=no -DBUILD_WSI_WAYLAND_SUPPORT=yes -DBUILD_WSI_XCB_SUPPORT=yes -DBUILD_WSI_XLIB_SUPPORT=yes -DVULKAN_HEADERS_INSTALL_DIR=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/tmp/portage/dev-util/vulkan-tools-1.2.135/work/vulkan-tools-1.2.135_build-abi_x86_64.amd64/gentoo_toolchain.cmake  /tmp/portage/dev-util/vulkan-tools-1.2.135/work/Vulkan-Tools-1.2.135
```

In particular notice that `BUILD_WSI_WAYLAND_SUPPORT` is enabled.

[build.log](https://github.com/KhronosGroup/Vulkan-Tools/files/4452706/build.log)

**Comment by Wunkolo** [comment]
I've been getting this exact error on a headless machine running Arch and it also causes it to not print anything.
Previously it would work too.

**Comment by charles-lunarg** [comment]
There is a known issue with the repo at tag 1.2.135 which causes vulkaninfo to exit early if it detects that the DISPLAY environment variable is not set. This has been fixed and is in the latest sdk.


That however would not explain the first error with vulkaninfo trying to create an XCB connection when under wayland.

**Comment by Wunkolo** [comment]
Thanks for the update. I was able to pull this git repo and build it myself and I am now getting a proper `vulkaninfo` output, despite the wayland cmake warnings mentioned earlier.
I'll wait for my distro's package to update.

**Comment by charles-lunarg** [comment]
The logic for whether to try to run X11 is based on the presence of the `DISPLAY` environment variable. This means if it is set and not empty, vulkaninfo will try to enable xcb/xlib. (only if it is reported available in the instance extension list).

```c
bool has_display = true;
const char *display_var = getenv("DISPLAY");
if (display_var == nullptr || strlen(display_var) == 0) {
        has_display = false;
        std::cerr << "'DISPLAY' environment variable not set... skipping surface info\n";
}
...
if (has_display) {
    if (inst.CheckExtensionEnabled(VK_KHR_XCB_SURFACE_EXTENSION_NAME)) {
          inst.AddSurfaceExtension(surface_ext_xcb);
    }
    if (inst.CheckExtensionEnabled(VK_KHR_XLIB_SURFACE_EXTENSION_NAME)) {
          inst.AddSurfaceExtension(surface_ext_xlib);
    }
}
```
For reference, the Wayland code has what should be a much more robust way to check if wayland is supported.
```c
wl_display *wayland_display = wl_display_connect(nullptr);
bool has_wayland_display = false;
if (wayland_display != nullptr) {
        wl_display_disconnect(wayland_display);
        has_wayland_display = true;
}
...
if (has_wayland_display) {
        inst.AddSurfaceExtension(surface_ext_wayland);
}
```
Whats not clear to me is why it tried to make an xcb connection when it shouldn't of. It might be that `DISPLAY` was set for unrelated reasons and the vulkan loader reported `VK_KHR_xcb_surface` when it shouldn't of.

**Comment by devurandom** [comment]
> Whats not clear to me is why it tried to make an xcb connection when it shouldn't of. It might be that `DISPLAY` was set for unrelated reasons and the vulkan loader reported `VK_KHR_xcb_surface` when it shouldn't of.

In my shells `DISPLAY` is indeed set. I assume this might be, because the session is started by SDDM (an X11-based display manager), but I am not sure.

Why the Vulkan loader reports this extension I do not even have a theory on.

**Comment by charles-lunarg** [comment]
@devurandom @Wunkolo Does this issue still apply?
Trying to clean up old issues, and this seems like it has either gone away, or is funky display driver issues that aren't clear as to what their cause is.

**Comment by Wunkolo** [comment]
Does not apply to me anymore no! Haven't had issues with vulkan info in years.

**Comment by devurandom** [comment]
I am currently not using Sway and I am no longer using Gentoo either. I will reopen, if/when I encounter this again.

**Comment by eathtespagheti** [comment]
The problem still exist on vulkan tools 1.3.263

On Xorg works file

**Comment by charles-lunarg** [comment]
@eathtespagheti Can you clarify exactly which issue is still being seen? Was the `DISPLAY` env-var set? How was `vulkaninfo` built?

**Comment by eathtespagheti** [comment]
@charles-lunarg sorry for the late reply, I've broke my back a week after writing that comment

Unsetting the `DISPLAY` variable solved the issue and `vulkaninfo` runs fine

**Comment by charles-lunarg** [comment]
Oh I hope you recover well then.

And glad to hear DISPLAY works for you.
