### ISSUE TITLE
Vulkaninfo target defines VK_LAYER_PATH

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Tools#388]
On Windows for Visual Studio cmake results there being `VK_LAYER_PATH=..\layers\Debug` in Environment, which is probably nonsense. Though I cannot find where this originates from. It does not seem to be in `CMakeLists.txt`.

**Comment by charles-lunarg** [comment]
A quick search revealed that the VK_LAYER_PATH is being setup in the `vulkaninfo.vcxproj.user` and the `cube.vcxproj.user` files. I have a feeling this is an artifact from before the great vulkan project reorganization, and thus cruft that is safe to remove.

**Comment by krOoze** [comment]
Oh snap. Didn't notice there were VS specific files outside `build`.
