### ISSUE TITLE
VK_DYNAMIC_STATE_RANGE_SIZE still used in cube.c, must be removed

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Tools#391]
I thought we had updated all of the Khronos repos  where the BEGIN_RANGE, END_RANGE, RANGE_SIZE tokens  were being used (per https://github.com/KhronosGroup/Vulkan-Docs/issues/1230), but apparently cube/cube.c in this repo still uses VK_DYNAMIC_STATE_RANGE_SIZE and that's breaking downstream consumers, see https://github.com/KhronosGroup/Vulkan-Headers/issues/117 . Judging by my very superficial scan of the file, the existing use of this token appears to be for an array containing dynamic state, and as constructed that array will not be large enough for dynamic state introduced by extensions, like VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT, so the code was probably in some fashion broken to begin with.

I don't *think* there are any other uses of these tokens in the repo but please check that as well.

**Comment by Tony-LunarG** [comment]
Fixed with #392
