### ISSUE TITLE
a python scripts can't be where It must be

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#398]
Hello,

a python scripts can't be where It must be :

the python scripts where It must be is called by this command line : 

'cmake -C herlper.cmake ..'

![cantcopypasttocubescripts](https://user-images.githubusercontent.com/30596513/81657370-1f27c180-9438-11ea-91a2-9bdadd6009dc.jpg)

![WhyICantPasteToCubeScriptsDirectory](https://user-images.githubusercontent.com/30596513/81657410-251da280-9438-11ea-8759-e3fed5564606.jpg)

I have tried the next command line adviced by BUILD.md and It missing a makefile this isn't the first error firstly reparing the python scripts error,

Thank you in advance for your help,

Regards.

Azaretdodo.

**Comment by karl-lunarg** [comment]
You need to follow the instructions in BUILD.md exactly.  I've just run the following commands with no problem:

```
cd /tmp
git clone git@github.com:KhronosGroup/Vulkan-Tools.git
cd Vulkan-Tools
mkdir build
cd build
../scripts/update_deps.py 
cmake -C helper.cmake ..
cmake --build .
./cube/vkcube
```
The build finished quickly and correctly and the last command ran the cube demo correctly.

One of your screenshots shows a `Vulkan-Tools/cube/scripts` directory.  This directory does not exist in this repository and you must have made some changes to your tree that should not have been made.

Perhaps you should try the above sequence of commands exactly.  Don't change anything.  Don't "fix" anything.

**Comment by Azaretdodo** [comment]
I will copy past my work on my GitHub (by mv) and do the build.md file ask to do 🙂
________________________________
De : Karl Schultz <notifications@github.com>
Envoyé : mardi 12 mai 2020 15:49
À : KhronosGroup/Vulkan-Tools <Vulkan-Tools@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-Tools] a python scripts can't be where It must be (#398)


You need to follow the instructions in BUILD.md exactly. I've just run the following commands with no problem:

cd /tmp
git clone git@github.com:KhronosGroup/Vulkan-Tools.git
cd Vulkan-Tools
mkdir build
cd build
../scripts/update_deps.py
cmake -C helper.cmake ..
cmake --build .
./cube/vkcube


The build finished quickly and correctly and the last command ran the cube demo correctly.

One of your screenshots shows a Vulkan-Tools/cube/scripts directory. This directory does not exist in this repository and you must have made some changes to your tree that should not have been made.

Perhaps you should try the above sequence of commands exactly. Don't change anything. Don't "fix" anything.

**Comment by Azaretdodo** [comment]
yes this time the python script doesn't happening error :)
