### ISSUE TITLE
where found google mock for add in your github it is ask by '../scripts/update_deps.py' command line !

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#399]
Hello,

where found google mock for add in your github it is ask by '../scripts/update_deps.py' command line !

Thank you in advance for your soon answer,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment]
From what I have seen so far, it really seems like most of your problems are coming from improperly building the repo or not having your system properly setup before you build the repo.

Please carefully read the BUILD.md document and make sure you have all proper dependencies install and that you are properly following the step-by-step instructions provided.
