### ISSUE TITLE
Mock icd: Add support for vkGetPhysicalDeviceFeatures2KHR pNext extension queries

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Tools#4]
**Issue by [jzulauf-lunarg](https://github.com/jzulauf-lunarg) (MIGRATED)**
_Friday Jan 26, 2018 at 22:40 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2374_

----

The mock_icd needs to report valid limit/feature information for all extensions it reported as supported.  Currently mock_icd ignores the pNext chain for vkGetPhysicalDeviceFeatures2KHR where the extension features are queried.  

However, when validation support is added for an extension, the features and limits need to be reported back with valid (for example guaranteed minimums given in the spec) values in order for validation to have proper bounds/feature checks and for validation testing to function correctly.

**Comment by spencer-lunarg** [comment]
closing this because 

1. `vkGetPhysicalDeviceFeatures2KHR` is implemented now
2. Profiles now can provide most features values
3. The value that Profile can not cover (https://github.com/KhronosGroup/Vulkan-Profiles/issues/352) can be done in MockICD on a case-by-case basis

**Comment by spencer-lunarg** [comment]
If it because need to support the Feature bits in the MockICD, something could be generated to set all `VkPhysicalDevice*Features` structs' `VkBool32` to true
