### ISSUE TITLE
vulkaninfo outputs failed with ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by bamps** [KhronosGroup/Vulkan-Tools#403]
Ubuntu 20.04 
no additional ppa and other sources.

vulkaninfo
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:477: failed with ERROR_INITIALIZATION_FAILED

There is also downstream bug:
https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1875483

**Comment by johnzupin** [comment]
That bug on launchpad was marked invalid. 

What is the graphics card you're using? Attach the output of `lspci -vvv > lspci.txt`

Also go ahead and attach the output of  `VK_LOADER_DEBUG=all vulkaninfo &> vulkaninfo.txt`

**Comment by bamps** [comment]
[vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/4648282/vulkaninfo.txt)
[lspci.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/4648284/lspci.txt)

**Comment by johnzupin** [comment]
Your AMD device (Radeon HD 6320) doesn't support Vulkan.

https://en.wikipedia.org/wiki/Vulkan_(API)#Compatibility (Expand the Hardware support tab)

**Comment by Stepan-Zubkov** [comment]
the same problem with opengl 4.6 (GeForce GT 440)
