### ISSUE TITLE
cube.cpp bad use of VK_FORMAT_UNDEFINED

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/Vulkan-Tools#422]
In cube.cpp there is code
```
    // If the format list includes just one entry of VK_FORMAT_UNDEFINED,
    // the surface has no preferred format.  Otherwise, at least one
    // supported format will be returned.
    if (formatCount == 1 && surfFormats[0].format == vk::Format::eUndefined) {
        format = vk::Format::eB8G8R8A8Unorm;
...
```
which is checking for condition which should never happen. Vulkan specification does not allow `VK_FORMAT_UNDEFINED` among returned formats.

**Comment by jeremyk-lunarg** [comment]
@tksuoran, while I am assigning this and issue #421 to someone internally, we are pretty busy at the moment.
Feel free to make a pull request to fix these issues.
It would be greatly appreciated.
