### ISSUE TITLE
apidump: Windows HWND should be considered an address/handle

### ISSUE THREAD

**Issue by null77** [KhronosGroup/Vulkan-Tools#434]
For the purposes of the "Hide Addresses" option Windows HWNDs change from run-to-run should should be replaced with "address" or 0. This would eliminate the noise when analyzing a trace diff.

**Comment by jeremyk-lunarg** [comment]
API Dump is located in the LunarG/VulkanTools [here](https://github.com/LunarG/VulkanTools).

Please close this issue and reopen it there.

**Comment by null77** [comment]
My bad. Thanks for the pointer.
