### ISSUE TITLE
Vulkan problem

### ISSUE THREAD

**Issue by Jeronymo123** [KhronosGroup/Vulkan-Tools#439]
I have problem with VulkanAPI. I open vulkaninfo in system32, but heissues error :
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.108

C:\VulkanSDKBuild\workspace\Khronos-Tools\repo\vulkaninfo\vulkaninfo.c:5586: failed with VK_ERROR_INITIALIZATION_FAILED

**Comment by Jeronymo123** [comment]
Videocard is Gts 450 2GB

**Comment by charles-lunarg** [comment]
You graphics card does not support vulkan, and vulkaninfo requires a driver on your system that supports vulkan. That means you need to get a newer graphics card, on that supports vulkan, or not use vulkan directly. There are ways to use vulkan on older GPU's, but that discussion is out of scope.
