### ISSUE TITLE
vulkaninfo: valid usage violation with query of VkSurfaceCapabilitiesFullScreenExclusiveEXT

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/Vulkan-Tools#472]
vulkaninfo has a query for the following surface capabilities for the VK_EXT_full_screen_exclusive extension:
```
	VkSurfaceCapabilitiesFullScreenExclusiveEXT:
	--------------------------------------------
		fullScreenExclusiveSupported = true
```

This capability is queried using the vkGetPhysicalDeviceSurfaceCapabilities2KHR function. The the following [VUID](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceCapabilities2KHR-pNext-02671) is not being followed by the vulkaninfo tool, which leads to undefined behavior:
```
VUID-vkGetPhysicalDeviceSurfaceCapabilities2KHR-pNext-02671
If a VkSurfaceCapabilitiesFullScreenExclusiveEXT structure is included in the pNext chain of pSurfaceCapabilities,
a VkSurfaceFullScreenExclusiveWin32InfoEXT structure must: be included in the pNext chain of pSurfaceInfo
```

Because of this the vulkaninfo report of fullScreenExclusiveSupported may not be accurate.

**Comment by charles-lunarg** [comment]
Fixed in #473
