### ISSUE TITLE
Incorrect function name for vkEnumeratePhysicalDevices

### ISSUE THREAD

**Issue by mgorchak-blackberry** [KhronosGroup/Vulkan-Tools#483]
Hi,

When debugged an ICD loader for QNX I have found this minor issue:

https://github.com/KhronosGroup/Vulkan-Tools/blob/c86cec54abe675845e709ad0b362bd8bffe18bf2/vulkaninfo/vulkaninfo.h#L722

string has name "vkEnumerateInstanceExtensionProperties" for function vkEnumeratePhysicalDevices().

Thanks.

**Comment by charles-lunarg** [comment]
Thanks for reporting it!
