### ISSUE TITLE
[FindVulkan.cmake] For CMAKE_SYSTEM_NAME="iOS" do not find_library vulkan

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Tools#487]
Because instead user code should be linked to `"$ENV{VULKAN_SDK}/MoltenVK/MoltenVK.xcframework/*/libMoltenVK.a"`. Linking to `*.dylib` leads to error in _Xcode_ when targeting to _iOS_.

**Comment by richard-lunarg** [comment]
What specifically are you tying to build for iOS in this repo? In general iOS is not supported yet. VulkanInfo can be built, but you must use the included XCode project. Builds of vkCube are available in the MoltenVK repo. I ask in case I do not understand properly what you are tying to accomplish?

**Comment by tomilov** [comment]
I just use Vulkan SDK, which contains `FindVulkan.cmake` from this repo on _macOS_. I use cmake as usual to generate Xcode project. For _macOS_ target it works. For _iOS_ doesn't.

 > In general iOS is not supported yet.

_iOS_ is supported: MoltenVK is a part of Vulkan infrastructure. Seems there are limitations on cmake side.

**Comment by richard-lunarg** [comment]
Yes, iOS has a Vulkan layered implementation, but none of the other Vulkan Tools or SDK components are available for iOS. CMake is only part of the issues. Additional iOS support for the SDK components are on our todo list. Currently there is no loader or layer support for iOS.

**Comment by charles-lunarg** [comment]
This repo has changed how it finds VulkanHeaders & the Vulkan-Loader towards using `find_package()` support for both. As such, I would like to ask if this is still an issue. 

As far as I know, `FindVulkan.cmake` is provided by cmake and not the SDK. While it does support the project layout in the SDK, it is not something LunarG maintains. (though, whether we should is an equally valid question that belongs elsewhere).

**Comment by charles-lunarg** [comment]
Because `FindVulkan.cmake` is no longer used, this should not be an issue. Closing.

**Comment by juan-lunarg** [comment]
> Because FindVulkan.cmake is no longer used, this should not be an issue. Closing.

To clarify this repo uses find_package(VulkanLoader) which I added recently. And FWIW I did check the FindVulkan.cmake maintained by kitware and it does seem to properly support iOS. So there shouldn't be any problems now.
