### ISSUE TITLE
cube: (Linux) Install image file and change cube(pp) to look for it in system dirs

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Tools#5]
The cube and cubepp demos have the restriction of expecting to find the texture image file (lunarg.ppm) in the same directory as the executable.  This restriction makes it infeasible to "install" to a system directory because the image file would have to go into a directory meant for executables and not data.

Choose a suitable system location that is consistent with the [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html) or equivalent standard.
Something like `/usr/share/vulkan/lunarg/cube/lunarg.ppm` as long as it follows conventions.

Modify the cube and cubepp applications to search the current directory first for lunarg.ppm and then this new system location.  The current directory has priority and the application should close if it cannot find the file in either location.

Modify the CMake install target to install this file to the selected location.

Note that we had this same request some time ago from a package maintainer, but we turned it down at that time because the compiled shader binaries needed to be installed as well, and we were unsure about doing that.

Since then, the cube(pp) packaging has changed so that the shader binaries are compiled into the program text, removing the need to install the shader binaries and reducing the number of auxiliary files to one.  It now seems more feasible to install this image file as described.

Another approach would be to store the contents of the texture image as a C source code file and compile the image into the program text.  But this seems clunky.

**Comment by mikew-lunarg** [comment]
[KTX](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/) can put the image directly into API native format w/o requiring a runtime conversion library. 
[xxd](https://spin.atomicobject.com/2013/09/09/5-unix-commands/) can be used for a one-time conversion of binary image data to C code.

**Comment by sarnex** [comment]
I am a maintainer for Gentoo and I am looking forward to the cube/cubepp demos being installed to the system.

Thank you.

**Comment by karl-lunarg** [comment]
Although we know how to handle installing the assets (texture image file), we've decided to compile the image data into the cube and cubepp applications, which avoids the need to handle the installation of the image file.  The Android version works this way, and it is just generally simpler to handle these simple demos when there are no other dependent files.

The PR for this issue will make these changes to cube(pp) and add them to the install target.

**Comment by sarnex** [comment]
Thanks Karl!
