### ISSUE TITLE
Cube demo should resize on VK_SUBOPTIMAL_KHR

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/Vulkan-Tools#506]
Based on [this discussion](https://github.com/KhronosGroup/MoltenVK/issues/1347#issuecomment-831722711), it looks like the Cube demo should resize on `VK_SUBOPTIMAL_KHR` in addition to `VK_ERROR_OUT_OF_DATE_KHR`.

**Comment by cforfang** [comment]
Note that on Android, if you don't handle pre-rotation (most apps don't) then you'll get `VK_SUBOPTIMAL_KHR` _every frame_ -- and so would definitely _not_ want to re-create the swap-chain solely based on `VK_SUBOPTIMAL_KHR` being returned. :)

**Comment by buzmeg** [comment]
The "correct" solution, as you point out, is "handle the pre-rotation."  Or have an Android-specific "fix" with *LOTS* of comments as to why that occurs on Android and what the "real" fix is supposed to be.

Side note: Is there an example somewhere showing people how to handle the pre-rotation on Android?  That sounds non-trivial.

Vulkan demos and apps are supposed to be exemplars that people learn from.  If "official" code doesn't do it right, end users are stuck scratching their head figuring out why "official" code doesn't actually work when they try to apply it to their problems.

**Comment by buzmeg** [comment]
I did go back through the code, this bug seems to predate any Android port--so I can't blame them.  :)

It exists as far back as commit 5aefef01499d849a090b5af5143efce45bf0ebea which has no mention of Android in cube.c

**Comment by Tony-LunarG** [comment]
It's easy enough to resize on VK_SUBOPTIMAL_KHR returned from QueuePresent, but it sounds like there is an Android consideration to take into account. Not being much of an Android programmer, can someone advise as to what should (or at a minimum, could) be done when vkcube running on Android gets VK_SUBOPTIMAL_KHR back from QueuePresent?
