### ISSUE TITLE
Vulkaninfo.exe of SDK running error

### ISSUE THREAD

**Issue by but0n** [KhronosGroup/Vulkan-Tools#52]
- Windows 10 64bit
 - Vulkan SDK 1.1.77.0

![image](https://user-images.githubusercontent.com/7625588/42548190-7990cd3e-84f8-11e8-8247-78252de42471.png)

---
Also cube and cubeapp doesn't work, nothing after execute, not even a window 😕 

Is there something wrong with ICD? I'm using AMD 480 graphic card, I noticed the `API Version` item is MISSING
![image](https://user-images.githubusercontent.com/7625588/42548216-a9f6bf2e-84f8-11e8-9f37-4b082ccd776c.png)

**Comment by karl-lunarg** [comment]
Both of the drivers look pretty old.  You might try updating at least the AMD driver.

It looks like you have a nvidia driver installed.  If you don't have a nvidia graphics card installed, you might try uninstalling the driver.

I think it is allowed for older drivers to not report an API Version.  If they do not, the loader assumes that they are 1.0 drivers.  So, I don't think that is the problem.

**Comment by lenny-lunarg** [comment]
> It looks like you have a nvidia driver installed. If you don't have a nvidia graphics card installed, you might try uninstalling the driver.

This seems like a likely cause of the problem to me. Old drivers generally did crash when a there were no installed GPUs that used them. Newer drivers shouldn't be loaded in this situation (whcih means no crash). Your Nvidia driver looks like its a little under a year old, so I wouldn't be surprised if its unable to handle a missing GPU. Removing it would be the best thing. but if you're doing something like regularly swapping out GPUs, then I would highly recommend making sure you update both drivers.

> I think it is allowed for older drivers to not report an API Version. If they do not, the loader assumes that they are 1.0 drivers. So, I don't think that is the problem.

It is. We also added the warning that you see in vulkaninfo to try to encourage people to update their manifest files to more recent versions, but there's still plenty of situations where people use the old versions.

**Comment by but0n** [comment]
@karl-lunarg @lenny-lunarg Thanks!
