### ISSUE TITLE
vkcube is expanding over the time ...

### ISSUE THREAD

**Issue by mgorchak-blackberry** [KhronosGroup/Vulkan-Tools#530]
I left the working vkcube in VK_PRESENT_MODE_IMMEDIATE_KHR mode for almost the whole day on the embedded device and noticed that the FPS started to drop very smoothly from 1380 to 1290 in 8 hours, it also became obvious that the cube had swollen a little. Centrifugal force? :D

It looks like a cumulative floating point error.

![screenshot-normal](https://user-images.githubusercontent.com/74101708/121973636-bf42cf00-cd4b-11eb-84d3-9b2c2fa6f185.jpg)
![screenshot-inflated](https://user-images.githubusercontent.com/74101708/121973640-bfdb6580-cd4b-11eb-92c2-12814fbdc25e.jpg)

**Comment by Tony-LunarG** [comment]
@mgorchak-blackberry can you say whether your cube was built from before or after a3d954fc13818cc07975dfd6030ad1bacb85e755 ?  Have you tried running cube like this before, and if so, is this new behavior?

**Comment by mgorchak-blackberry** [comment]
I'm pretty sure this patch was not included in the vkcube build. I will apply it and let it run overnight. Will post results tomorrow. Thank you!

**Comment by mgorchak-blackberry** [comment]
I ran it too late yesterday, need a little bit more time, but I do not observe even any minor FPS drops (it was before because cube required more fragment shader works due to expansion). FPS is stable for 4 hours already.

Still testing...

**Comment by mgorchak-blackberry** [comment]
I think the problem was fixed and I will close the issue, 6+ hours of run shows no expansion issue, FPS is stable, no decreases were observed.
