### ISSUE TITLE
vulkaninfo modifies VkFormatProperties reported by the driver

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-Tools#535]
In preparing the `ArrayOfVkFormatProperties`, `vulkaninfo` will sort and prune the list actually returned by the driver.

Any format with 0s everywhere,e.g.:
```
{'formatID': 4, 'linearTilingFeatures': 0, 'optimalTilingFeatures': 0, 'bufferFeatures': 0}
```
will be silently pruned.  And all formats will be sorted by `vulkaninfo`'s processing order (which is roughly equivalent to sorting by `formatID`), regardless of what order they are reported by the driver (which can cause confusion, as some programs use the first `VkFormat` reported by the driver, which will not necessarily be the first `VkFormat` reported by `vulkaninfo`).

This was unexpected to me, as (without other documentation to the contrary) I'd assumed that `vulkaninfo` simply returned whatever the driver returned, without validation or modification of any kind (only formatting).

I prefer that `vulkaninfo` adhere to the simplest convention, and return what the driver reports without any modification or sorting.  This makes the tool useful for driver writers (who need to know exactly what their driver is reporting) as well as for users.  It also makes use of `devsim` predictable.

If `vulkaninfo` is going to validate and prune what the driver reports, then we have to consider why it's not validating and pruning *other* fields that the driver reports.  Is the use model that `vulkaninfo` ensures clean, legal output?  Or that `vulkaninfo` just reports what it sees and leaves validation to other components like **Vulkan-ValidationLayers**?

If `vulkaninfo` is going to stray from the "obvious", its documentation will have to be updated to reflect that.

If `vulkaninfo` is going to change to *stop* pruning and validating, we'll probably have to add a switch, to avoid breaking legacy behavior, unless we can convince ourselves that the legacy behavior was wrong or that no one is relying on it.

**Comment by lunarpapillo** [comment]
BTW, this affects **LunarG/VulkanTools** testing for the `devsim` layer, which uses `devsim` to modify the reported capabilities of a device and `vulkaninfo` to report them.  @jeremyk-lunarg is considering switching to a **GoogleTest** structure for testing instead, which might eliminate or reduce the need for Python script testing.

**Comment by lunarpapillo** [comment]
Thanks for the clarification; let me restate to see whether I understand correctly.

`vulkaninfo` looks like it's reporting the value of a query when it lists the driver formats, but it is not - it's just querying the driver for all known formats one at a time and reporting the ones that are supported.

When `devsim` appears to override `ArrayOfVkFormatProperties`, that's actually not a real field returned by the driver that is being overridden, but a synthesized field.  As such, the returned value is a combination of what the driver actually supports and what `devsim` is overriding with (contrary to `devsim` documentation, which explicitly says that the `ArrayOf` elements are complete overrides and not combined with the underlying driver values in any way).

If that's all more or less correct, it's really the `devsim` documentation that needs a major overhaul, yes?

Does the same thing happen with the other `ArrayOf` fields that can be overridden by `devsim`?  E.g., `ArrayOfVkQueueFamilyProperties`?

**Comment by jeremyk-lunarg** [comment]
The query for `VkQueueFamilyProperties` does return an array of values, but Devsim does not do any special combining with this array.  It does do combining with `VkExtensionProperties`, `VkPresentModesKHR`, and `VkSurfaceFormatsKHR`. Those last 2 are new additions as of this morning.

**Comment by charles-lunarg** [comment]
I'm going to close this issue since I think vulkaninfo can/should address. It appears that DevSim specific logic depends on the kind of array being processed, and should have its own follow up issue dedicated to the topic. Feel free to reopen if the role vulkaninfo plays wasn't properly addressed (eg, I think there are no changes needed to vulkaninfo).
