### ISSUE TITLE
vkcube and handling memory allocation from zero-sized heaps

### ISSUE THREAD

**Issue by mgorchak-blackberry** [KhronosGroup/Vulkan-Tools#559]
One of the silicon vendors have provided us Vulkan drivers for QNX for validation purpose and it seems that vkcube cannot handle this situation properly. The driver lists two heaps (vulkaninfo dump):

memoryHeaps: count = 2
        memoryHeaps[0]:
                size   = 0 (0x00000000) (0.00 B)
                budget = 0 (0x00000000) (0.00 B)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT
        memoryHeaps[1]:
                size   = 268435456 (0x10000000) (256.00 MiB)
                budget = 0 (0x00000000) (0.00 B)
                usage  = 0 (0x00000000) (0.00 B)
                flags: count = 1
                        MEMORY_HEAP_DEVICE_LOCAL_BIT

From the specification point of view this is a valid configuration (for example the chip doesn't have dedicated memory, only UMA, so it is zero in the current hardware configuration).

Validation layer complains about this:

ERROR : VALIDATION - Message Id Number: -375211665 | Message Id Name: VUID-vkAllocateMemory-pAllocateInfo-01713
        Validation Error: [ VUID-vkAllocateMemory-pAllocateInfo-01713 ] Object 0: handle = 0x37dcd54650, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe9a2b96f | vkAllocateMemory: attempting to allocate 4214784 bytes from heap 0,but size of that heap is only 0 bytes. The Vulkan spec states: pAllocateInfo->allocationSize must be less than or equal to VkPhysicalDeviceMemoryProperties::memoryHeaps[memindex].size where memindex = VkPhysicalDeviceMemoryProperties::memoryTypes[pAllocateInfo->memoryTypeIndex].heapIndex as returned by vkGetPhysicalDeviceMemoryProperties for the VkPhysicalDevice that device was created from. (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkAllocateMemory-pAllocateInfo-01713)

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 37dcd54650

The driver itself has a compensating bug, allocation from zero-sized heap always succeeds. So this let vkcube run smooth on this hardware.

Should vkcube cube handle this situation? Should we ask vendor to remove zero-sized heap to be listed?

**Comment by Tony-LunarG** [comment]
The spec tells cube to select the first one. Looking at https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#memory-device-properties the memory types returned from Get*MemoryRequirements are ordered:

For each pair of elements X and Y returned in memoryTypes, X must be placed at a lower index position than Y if:
* the set of bit flags returned in the propertyFlags member of X is a strict subset of the set of bit flags returned in the propertyFlags member of Y; or
* the propertyFlags members of X and Y are equal, and X belongs to a memory heap with greater performance (as determined in an implementation-specific manner) ; or
* the propertyFlags members of Y includes VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD or VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD and X does not

This, and the example in the spec that follows boils down to "pick the lowest memory type that has the memory properties that you need". In neither the example in the above section, nor the example in https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_NV_external_memory_rdma does the code do anything other than pick the first available memory type with the desired properties, and neither consider the size of the heap the memory type is in.
Admittedly, in theory, allocations should check for VUID 01713, but in practice, in the examples in Vulkan-Samples, and in the spec examples, I just don't see it done.
Again, I don't think the driver should be returning a memory type in a zero sized heap, and it most certainly should not be returning it _first_

**Comment by Tony-LunarG** [comment]
Closing, please re-open or submit another issue if you still feel there are problems
