### ISSUE TITLE
Windows Validation Layers Missing

### ISSUE THREAD

**Issue by Aleksbgbg** [KhronosGroup/Vulkan-Tools#566]
I had to install a fresh version of Windows due to a corrupted boot sector. However, when I installed the VulkanSDK on my fresh install, suddenly the validation layers were missing from my installation. I have tried reinstalling the SDK multiple times and restarting after uninstalling and installing to ensure it's not a Windows issue.

Here is a screenshot from the vulkan configurator:
![image](https://user-images.githubusercontent.com/31630318/133254021-cce22be3-8104-4cc4-b07e-392afb66f313.png)
As you can see, I only have one available layer, and the validation layer I had enabled before (`VK_LAYER_KHRONOS_validation`) is nowhere to be seen. Even though the validation layer is forced on by the configurator, this doesn't work in my app or in `vkcube`.

How can I remedy this issue? Is this a fault in the installer?

**Comment by jeremyk-lunarg** [comment]
This repo is for Vulkan-Tools specific issues, not SDK issues.
Please post SDK related issues to https://vulkan.lunarg.com/issue/home.
