### ISSUE TITLE
vulkaninfo json reporting does not include 1.1 and 1.2 information

### ISSUE THREAD

**Issue by trevordblack** [KhronosGroup/Vulkan-Tools#577]
The `vulkaninfo` utility is capable of querying for and reporting 1.1 and 1.2 information when the user outputs in a human readable format.
This same utility is seemingly querying for 1.1 and 1.2 information, but fails to actually report it when the user chooses to output a json file.
This came as a surprise when I was expecting the json reporting from vulkaninfo to match the schema being used at vulkan.gpuinfo.org
Sascha Willem's VulkanCapsViewer appears to have a strict superset of the data reported from the json output of vulkaninfo.
The disparity between the human readable reporting of vulkaninfo and the json reporting feels like something that should be addressed.

**Comment by charles-lunarg** [comment]
This has been addressed by making vulkaninfo print out a file corresponding to the profiles schema, and is apart of the autogen so it includes minor versions and extensions. It might not be suitable for your purposes but does fill the hole described by the issue.
