### ISSUE TITLE
Missing VkPhysicalDeviceVulkan12Features on GPU that supports it

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/Vulkan-Tools#595]
Here is the [report](https://github.com/gfx-rs/wgpu/files/7610825/vulcaninfo.txt).
Instance Vulkan version is 1.1
Physical device Vulkan version is 1.2

The instance supports `VK_KHR_get_physical_device_properties2`, so I expect the relevant output to be generated.
However it's not queried by `vulkaninfo` because of this check:
https://github.com/KhronosGroup/Vulkan-Tools/blob/a01b76b1686f882e2a0ec05426ab2bff58580c92/vulkaninfo/vulkaninfo.h#L1505

I believe this check is wrong. We shouldn't mix device and instance versions together.

**Comment by charles-lunarg** [comment]
Looking at the code, this does indeed appear to be wrong. I will try to fix it up by simply passing in the api_version directly. This could also be simplified by making the codegen a bit clearer, as this was commented upon in a recent code review for the 'many small fixes' PR I have in flight.
