### ISSUE TITLE
vulkaninfo: shouldn't include extension structure if VK_EXT_memory_budget not supported

### ISSUE THREAD

**Issue by cdotstout** [KhronosGroup/Vulkan-Tools#602]
In the Intel Mesa/Anvil driver, if support for VK_EXT_memory_budget is disabled, an assertion (debug build) is triggered by vulkaninfo:

cstout@cstout-Switch-SA5-271:~/projects/Vulkan-Tools/build$ VK_ICD_FILENAMES=$HOME/projects/mesa/build/install/share/vulkan/icd.d/intel_icd.x86_64.json ./vulkaninfo/vulkaninfo 
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vulkaninfo: ../src/intel/vulkan/anv_device.c:2682: anv_get_memory_budget: Assertion `0 < heap_budget && heap_budget <= heap_size' failed.
Aborted (core dumped)

**Comment by charles-lunarg** [comment]
My understanding is that drivers/layers/loaders must skip over anything it doesn't support or recognize.
> Any component of the implementation (the loader, any enabled layers, and drivers) must skip over, without processing (other than reading the sType and pNext members) any extending structures in the chain not defined by core versions or extensions supported by that component.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap3.html#fundamentals-validusage-sType

While I am willing to modify the source to not include extensions that aren't supported, my understanding is that it shouldn't be necessary from a spec point of view.

**Comment by cdotstout** [comment]
I understand there's been some discussion on this topic (see https://gitlab.khronos.org/vulkan/vulkan/-/issues/2442), and you may be right that ANV should be skipping.  But if this topic continues to be a grey area vulkaninfo should probably model the "better" app behavior.

**Comment by charles-lunarg** [comment]
Thats a good point, and well, not crashing is better than crashing in most cases, here included.
I acquiesce to your point, and agree that vulkaninfo shouldn't add pNext chain structures for extensions it knows aren't supported.
