### ISSUE TITLE
vkcube and vkcubepp lag when resizing (Ubuntu 20.04)

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/Vulkan-Tools#621]
As title says, both applications lag when resized through the edges of the window. It also alternates between black screen and what it should be rendered.

I also found that while vkcube is open, if I resize other windows, they lag too, and a lot. If vkcube is not open, there's barely any lag while resizing other windows.

I'm unsure if this could be related to vkcube or there may be a bigger issue on the driver side of my machine. Creating this issue so it gets logged somewhere since this was found while testing SDK 1.3.204.

Platform: Ubuntu 20.04
GPU: Nvidia RTX 3070 Ti

**Comment by aitor-lunarg** [comment]
That's good to hear, then I think we can safely close the issue?

**Comment by KarenGhavam-lunarG** [comment]
I believe so and am going to close it.
