### ISSUE TITLE
Cube demo assumes linear image support that may not exist

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Tools#66]
The cube demo checks to see if linear textures can be sampled from directly (when `use_staging_buffer` is not set) and if supported creates such a texture directly.

If the staging flag is enabled or linear textures can't be sampled from then it does a staged upload to an optimally tiled texture. The staging resource is not a buffer though, it still creates a linear image to copy from.

The spec only requires optimal support for images it doesn't require any linear support at all, so it's valid for it to be impossible to create such a linear image - instead the code should create a buffer and use `vkCmdCopyBufferToImage`.

**Comment by Tony-LunarG** [comment]
Fixed with PR #71
