### ISSUE TITLE
VulkanRT-Installer.exe missing ASLR

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-Tools#68]
I downloaded [latest Vulkan runtime installer](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.82.1/windows/VulkanRT-1.1.82.1-Installer.exe)
and tested it with Microsoft binskim tool:

`BinSkim.exe analyze VulkanRT-1.1.82.1-Installer.exe -verbose > out_SDK_1_1_82_1.txt`

It shows following security issue:

> VulkanRT-1.1.82.1-Installer.exe: error BA2009: 'VulkanRT-1.1.82.1-Installer.exe' is marked as DYNAMICBASE but relocation data has been stripped from the image, preventing address space layout randomization. 

I **do not see** this message in locally built installer using [Vulkan-Tools winrt sources](https://github.com/KhronosGroup/Vulkan-Tools/blob/master/winrt/README.md). 

Is this installer executable additionally stripped before being uploaded to LunarXchange?

**Comment by lenny-lunarg** [comment]
Does the runtime installer you built yourself run if you enable system wide ASLR (address speace layout randomization) on your OS? As I recall, we had a problem where systems that mandated ASLR couldn't run the installer. I don't remember what our solution had been, but it is possible that you're right. If your build does run fine with system-wide ASLR, then we might need to see what we're doing differently and change it. If it doesn't run with system-wide ASLR, then we'd need to solve that problem in order to make other changes.

**Comment by dor666** [comment]
Sorry for delay, I was offline. 
Your correct, my locally compiled installer is not launching when system wide ASLR is enabled.
This is strange for me, I would expect opposite (since "relocation data has been stripped from the image").

**Comment by dor666** [comment]
It looks like ASLR is not working at all.

Both publicly available installer:
![aslr_downloaded_installer](https://user-images.githubusercontent.com/1740971/46071371-270df180-c180-11e8-9a8e-bd4da99c6484.PNG)

And compiled by me (with relocation not stripped)
![aslr_compiled_installer](https://user-images.githubusercontent.com/1740971/46071265-ea41fa80-c17f-11e8-898d-2564487ce22f.PNG)

All load exe image to 0x400000.
It is the same if I globally enable ASLR and disable it. (But my exe is crashing when mandatory ASLR is enabled).

Public installer have stripped ".reloc" section so it will not be rebased in my understanding. 
I don't know why locally compiled is not rebased.

**Comment by dor666** [comment]
I think that reason for crash (and ASLR not working in any case) is that _.rsrc_ section overlaps _.reloc_ section (See Raw Data pointers and sizes).
![image](https://user-images.githubusercontent.com/1740971/46142150-45462100-c256-11e8-951f-354511910025.png)

I think that something in NSIS_Security.patch should be added, so sections will not overlap.

**Comment by jjulianoatnv** [comment]
Is there a remaining use of VulkanRT-Installer.exe such that this issue remains relevant?

Modern IHV display drivers have stopped using VulkanRT-Installer.exe.  At least this is true of one of the three Windows IHVs shipping Vulkan. I assume it is true of the other IHVs too.

If the only remaining use of VulkanRT-Installer.exe is the Vulkan SDK, then is that sufficient concern to keep the issue open for only the Vulkan SDK?

**Comment by KarenGhavam-lunarG** [comment]
With the next windows SDK release, the VulkanRT-installer is removed from the windows SDK. The windows SDK will still install vulkaninfo but not the Vulkan loader.

The VulkanRT installer will still be available for a separate download, but it is commented that most people do not need to install it but rather get their Vulkan Loader from IHV driver updates.

**Comment by jeremyk-lunarg** [comment]
Should I close this issue since it has such a small use case then?

**Comment by KarenGhavam-lunarG** [comment]
> Modern IHV display drivers have stopped using VulkanRT-Installer.exe. At least this is true of one of the three Windows IHVs shipping Vulkan. I assume it is true of the other IHVs too.

It is true for the other IHVs as well. So the remaining use case for the VulkanRT-Installer is really small. I think it is OK to close it.
