### ISSUE TITLE
vulkaninfo: Build failed

### ISSUE THREAD

**Issue by shivania2** [KhronosGroup/Vulkan-Tools#702]
I am getting following error while build vulkaninfo package

`2022-11-08 09:30:53,824 - build-vulkan-tools-1.3.231.1 -       |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_EXT_IMAGE_ROBUSTNESS_EXTENSION_NAME
../vulkaninfo/generated/vulkaninfo.hpp:4245:13: error: 'VkPhysicalDevicePipelineRobustnessFeaturesEXT' was not declared in this scope; did you mean 'DumpVkPhysicalDevicePipelineRobustnessFeaturesEXT'?
 4245 |             VkPhysicalDevicePipelineRobustnessFeaturesEXT* props = (VkPhysicalDevicePipelineRobustnessFeaturesEXT*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             DumpVkPhysicalDevicePipelineRobustnessFeaturesEXT
../vulkaninfo/generated/vulkaninfo.hpp:4245:60: error: 'props' was not declared in this scope
 4245 |             VkPhysicalDevicePipelineRobustnessFeaturesEXT* props = (VkPhysicalDevicePipelineRobustnessFeaturesEXT*)structure;
      |                                                            ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4245:115: error: expected primary-expression before ')' token
 4245 |             VkPhysicalDevicePipelineRobustnessFeaturesEXT* props = (VkPhysicalDevicePipelineRobustnessFeaturesEXT*)structure;
      |                                                                                                                   ^
../vulkaninfo/generated/vulkaninfo.hpp:4306:33: error: 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_EXT' was not declared in this scope; did you mean 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_ARM'?
 4306 |         if (structure->sType == VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_EXT &&
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_ARM
../vulkaninfo/generated/vulkaninfo.hpp:4307:159: error: 'VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME' was not declared in this scope; did you mean 'VK_ARM_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME'?
 4307 |            (gpu.CheckPhysicalDeviceExtensionIncluded(VK_ARM_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME) || gpu.CheckPhysicalDeviceExtensionIncluded(VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME))) {
      |                                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                               VK_ARM_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME
../vulkaninfo/generated/vulkaninfo.hpp:4308:13: error: 'VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT' was not declared in this scope; did you mean 'VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesARM'?
 4308 |             VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT* props = (VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesARM
../vulkaninfo/generated/vulkaninfo.hpp:4308:76: error: 'props' was not declared in this scope
 4308 |             VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT* props = (VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT*)structure;
      |                                                                            ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4308:147: error: expected primary-expression before ')' token
 4308 |             VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT* props = (VkPhysicalDeviceRasterizationOrderAttachmentAccessFeaturesEXT*)structure;
      |                                                                                                                                                   ^
../vulkaninfo/generated/vulkaninfo.hpp:4415:33: error: 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_FEATURES_EXT' was not declared in this scope; did you mean 'VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_FLOAT_2_FEATURES_EXT'?
 4415 |         if (structure->sType == VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_FEATURES_EXT &&
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_FLOAT_2_FEATURES_EXT
../vulkaninfo/generated/vulkaninfo.hpp:4416:54: error: 'VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME' was not declared in this scope; did you mean 'VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME'?
 4416 |            (gpu.CheckPhysicalDeviceExtensionIncluded(VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME))) {
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME
../vulkaninfo/generated/vulkaninfo.hpp:4417:13: error: 'VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT' was not declared in this scope; did you mean 'DumpVkPhysicalDeviceShaderModuleIdentifierFeaturesEXT'?
 4417 |             VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT* props = (VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             DumpVkPhysicalDeviceShaderModuleIdentifierFeaturesEXT
../vulkaninfo/generated/vulkaninfo.hpp:4417:64: error: 'props' was not declared in this scope
 4417 |             VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT* props = (VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT*)structure;
      |                                                                ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4417:123: error: expected primary-expression before ')' token
 4417 |             VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT* props = (VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT*)structure;
      |                                                                                                                           ^
../vulkaninfo/generated/vulkaninfo.hpp: In function 'void chain_iterator_format_properties2(Printer&, AppGpu&, void*)':
../vulkaninfo/generated/vulkaninfo.hpp:4604:33: error: 'VK_STRUCTURE_TYPE_SUBPASS_RESOLVE_PERFORMANCE_QUERY_EXT' was not declared in this scope
 4604 |         if (structure->sType == VK_STRUCTURE_TYPE_SUBPASS_RESOLVE_PERFORMANCE_QUERY_EXT &&
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4605:54: error: 'VK_EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME' was not declared in this scope
 4605 |            (gpu.CheckPhysicalDeviceExtensionIncluded(VK_EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME))) {
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4606:13: error: 'VkSubpassResolvePerformanceQueryEXT' was not declared in this scope; did you mean 'DumpVkSubpassResolvePerformanceQueryEXT'?
 4606 |             VkSubpassResolvePerformanceQueryEXT* props = (VkSubpassResolvePerformanceQueryEXT*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             DumpVkSubpassResolvePerformanceQueryEXT
../vulkaninfo/generated/vulkaninfo.hpp:4606:50: error: 'props' was not declared in this scope
 4606 |             VkSubpassResolvePerformanceQueryEXT* props = (VkSubpassResolvePerformanceQueryEXT*)structure;
      |                                                  ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4606:95: error: expected primary-expression before ')' token
 4606 |             VkSubpassResolvePerformanceQueryEXT* props = (VkSubpassResolvePerformanceQueryEXT*)structure;
      |                                                                                               ^
../vulkaninfo/generated/vulkaninfo.hpp: In function 'void chain_iterator_queue_properties2(Printer&, AppGpu&, void*)':
../vulkaninfo/generated/vulkaninfo.hpp:4624:33: error: 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_QUERY_RESULT_STATUS_PROPERTIES_KHR' was not declared in this scope; did you mean 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_QUERY_RESULT_STATUS_PROPERTIES_2_KHR'?
 4624 |         if (structure->sType == VK_STRUCTURE_TYPE_QUEUE_FAMILY_QUERY_RESULT_STATUS_PROPERTIES_KHR &&
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 VK_STRUCTURE_TYPE_QUEUE_FAMILY_QUERY_RESULT_STATUS_PROPERTIES_2_KHR
../vulkaninfo/generated/vulkaninfo.hpp:4626:13: error: 'VkQueueFamilyQueryResultStatusPropertiesKHR' was not declared in this scope; did you mean 'VkQueueFamilyQueryResultStatusProperties2KHR'?
 4626 |             VkQueueFamilyQueryResultStatusPropertiesKHR* props = (VkQueueFamilyQueryResultStatusPropertiesKHR*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             VkQueueFamilyQueryResultStatusProperties2KHR
../vulkaninfo/generated/vulkaninfo.hpp:4626:58: error: 'props' was not declared in this scope
 4626 |             VkQueueFamilyQueryResultStatusPropertiesKHR* props = (VkQueueFamilyQueryResultStatusPropertiesKHR*)structure;
      |                                                          ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4626:111: error: expected primary-expression before ')' token
 4626 |             VkQueueFamilyQueryResultStatusPropertiesKHR* props = (VkQueueFamilyQueryResultStatusPropertiesKHR*)structure;
      |                                                                                                               ^
../vulkaninfo/generated/vulkaninfo.hpp:4632:33: error: 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_VIDEO_PROPERTIES_KHR' was not declared in this scope; did you mean 'VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR'?
 4632 |         if (structure->sType == VK_STRUCTURE_TYPE_QUEUE_FAMILY_VIDEO_PROPERTIES_KHR &&
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR
../vulkaninfo/generated/vulkaninfo.hpp:4634:13: error: 'VkQueueFamilyVideoPropertiesKHR' was not declared in this scope; did you mean 'DumpVkQueueFamilyVideoPropertiesKHR'?
 4634 |             VkQueueFamilyVideoPropertiesKHR* props = (VkQueueFamilyVideoPropertiesKHR*)structure;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             DumpVkQueueFamilyVideoPropertiesKHR
../vulkaninfo/generated/vulkaninfo.hpp:4634:46: error: 'props' was not declared in this scope
 4634 |             VkQueueFamilyVideoPropertiesKHR* props = (VkQueueFamilyVideoPropertiesKHR*)structure;
      |                                              ^~~~~
../vulkaninfo/generated/vulkaninfo.hpp:4634:87: error: expected primary-expression before ')' token
 4634 |             VkQueueFamilyVideoPropertiesKHR* props = (VkQueueFamilyVideoPropertiesKHR*)structure;`

**Comment by charles-lunarg** [comment]
These errors typically stem from not using the Vulkan-Headers that the source code was generated against. 
The intended way to build the project is to run `python scripts/update_deps.py` in the build folder, which generates `helper.cmake`. Then, when you run `cmake` you add the `-C helper.cmake` argument to it, so it 'knows' where the header install dir is located.

The full list of build commands looks something like this - check the BUILD.md for further info.
```
cd Vulkan-Tools 
mkdir build
cd build
python ../scripts/update_deps.py
cmake .. -C helper.cmake
```

**Comment by shivania2** [comment]
Thanks You for the immediate response.
I am able to build the package with the help of above command and instruction given in BUILD.md.
