### ISSUE TITLE
Compiler warning on 32-bit architectures: cast to/from pointer from/to integer of different size

### ISSUE THREAD

**Issue by smcv** [KhronosGroup/Vulkan-Tools#703]
While building Vulkan-Tools sdk-1.3.231.1 for Steam Runtime 2 'soldier' (derived from Debian 10), 32-bit x86 ("i386" ABI), using gcc 8:

```
[  122s] cd /usr/src/packages/BUILD/build/cube && /usr/bin/cc -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_XCB_KHR -I/usr/src/packages/BUILD/build/cube -I/usr/src/packages/BUILD/cube -I/usr/src/packages/BUILD/build/cube/.. -g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -fvisibility=hidden -o CMakeFiles/vkcube.dir/cube.c.o -c /usr/src/packages/BUILD/cube/cube.c
[  122s] /usr/src/packages/BUILD/cube/cube.c: In function 'debug_messenger_callback':
[  122s] /usr/src/packages/BUILD/cube/cube.c:533:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
[  122s]                          (void *)(pCallbackData->pObjects[object].objectHandle), pCallbackData->pObjects[object].pObjectName);
[  122s]                          ^
[  122s] /usr/src/packages/BUILD/cube/cube.c:537:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
[  122s]                          (void *)(pCallbackData->pObjects[object].objectHandle));
[  122s]                          ^
[  122s] /usr/src/packages/BUILD/cube/cube.c: In function 'demo_draw_build_cmd':
[  122s] /usr/src/packages/BUILD/cube/cube.c:770:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
[  122s]              .objectHandle = (uint64_t)cmd_buf,
[  122s]                              ^
[  124s] [ 27%] Linking C executable vkcube
```

Some toolchains make warnings like these into an error, causing build failure.

**Comment by smcv** [comment]
If I'm reading correctly, line 770 is storing a pointer (`cmd_buf`) in a `uint64_t`, to be printed later for debugging purposes. On 64-bit architectures like x86_64 it fits exactly and does not cause a warning. On 32-bit architectures like i386, this is a widening conversion, which is lossless but provokes a compiler warning in case it isn't what you meant. On more obscure architectures like CHERI, pointers can be larger than 64 bits (CHERI uses 128-bit tagged pointers) which means this is a narrowing conversion that loses the high bits, but if printing only the low 64 bits is OK for your debugging purposes then it's good enough.

If the size change is acceptable, it should be possible to suppress the compiler warning with something like this:

```diff
-             .objectHandle = (uint64_t)cmd_buf,
+             .objectHandle = (uintptr_t)cmd_buf,
```

Similarly, if I'm reading correctly, lines 533 and 537 are taking the number from the `uint64_t` and telling `printf` to print it as though it was a pointer, presumably in order to get any special formatting that the platform might apply to pointers (printing `NULL` as `(null)`, or printing non-null pointers as hex padded to an appropriate width, or whatever). On 64-bit, again this is lossless, but on 32-bit this is a narrowing conversion which loses the high bits of the `uint64_t`, causing a compiler warning - although in this case I think we have domain-specific knowledge that the high bits are uninteresting?

Again, if the size change is acceptable, it should be possible to suppress the compiler warning with an intermediate cast:

```diff
-                         (void *)(pCallbackData->pObjects[object].objectHandle));
+                         (void *)(uintptr_t)(pCallbackData->pObjects[object].objectHandle));
```

although I'm not sure whether this will do the right thing on architectures with very large pointers like CHERI.

Alternatively, vkcube could print the `objectHandle` as a 64-bit hex integer with format `"%" PRIx64` instead of printing it as a pointer.

**Comment by smcv** [comment]
> Since debug utils expects 64 bit ints, when giving data to the API, all objects handles need to be converted to uint64_t (or something convertable to it) which may require some sort of specialization for dispatchable handles on 32 bit.

For 32- and 64-bit architectures, `.objectHandle = (uintptr_t)cmd_buf` works fine, doesn't generate warnings and is lossless. `uintptr_t` is the same size as a pointer by definition.

For large-pointer architectures like CHERI, assigning the `uintptr_t` to the 64-bit `objectHandle` will truncate the pointer value to its least-significant 64 bits - which is unavoidable, we can't fit a more-than-64-bit value into a 64-bit type. That's probably adequate for debug info though?

> Inside the callback, it would be prudent to also special case the printing

What's the purpose of printing this thing? Is it just so a developer can correlate the object handle with the pointers they see in `gdb`, or with an object handle seen in a previous debug message, or similar, with no particular formatting requirements?

If it's that, then using `printf("0x%" PRIx64, pObjects[object].objectHandle)` seems like the simplest way to display an opaque 64-bit number that might (or might not!) secretly be a pointer, in hex. It seems to me that going via `"%p"` can only lose information (if your 64-bit number is larger than a pointer), and cannot really be an improvement vs. `PRIx64`, because any information outside the 64-bit range was already lost by the time we get here. The only advantage that I see of `"%p"` is if some platform pretty-prints pointers in some way that makes them more developer-friendly than an opaque 64-bit integer?

**Comment by charles-lunarg** [comment]
CHERI support is a 'nice to have' but not of particular concern to me. The fact that the API uses 64 bit here means there is no good solution for such a platform without changing the Vulkan API itself here. 

The pseudocode I wrote was trying to convey the idea of special casing dispatchable handles to print pointers. I forgot to finish the rest of the function, so I'll copy/paste an actual code solution describing what I was thinking. (and could be used in a PR).
```c
for (uint32_t object = 0; object < pCallbackData->objectCount; ++object) {
    sprintf(tmp_message, "\t\tObject[%d] - %s", object, string_VkObjectType(pCallbackData->pObjects[object].objectType));

    VkObjectType t = pCallbackData->pObjects[object].objectType;
    if (t == VK_OBJECT_TYPE_INSTANCE || t == VK_OBJECT_TYPE_PHYSICAL_DEVICE || t == VK_OBJECT_TYPE_DEVICE ||
        t == VK_OBJECT_TYPE_COMMAND_BUFFER || t == VK_OBJECT_TYPE_QUEUE) {
        sprintf(tmp_message, ", Handle %p", (void *)(pCallbackData->pObjects[object].objectHandle));
    } else {
        sprintf(tmp_message, ", Handle Ox%" PRIx64, (pCallbackData->pObjects[object].objectHandle));
    }

    if (NULL != pCallbackData->pObjects[object].pObjectName && strlen(pCallbackData->pObjects[object].pObjectName) > 0) {
        sprintf(tmp_message, ", Name \"%s\"", pCallbackData->pObjects[object].pObjectName);
    }
    sprintf(message, "\n");
    strcat(message, tmp_message);
}
```
Yes, I believe the purpose is to allow the user to see all the objects involved with the current message. In addition, vkcube is often used to 'showcase' how to use extensions, thus I suspect that this code was written to show off how to use the API as well.
