### ISSUE TITLE
consider upgrading to c++17

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-Tools#711]
In https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4514 it was suggested that we move all ecosystem components to a newer c++ standard. Is this feasible for Vulkan-Tools?

**Comment by charles-lunarg** [comment]
Feasible? Yes, very much. Mainly involves setting the standard to something newer and fixing any issues that comes up.

As far as 'cleaning up the code to *use* C++17', that wont happen anytime soon since it isn't a high priority.

**Comment by jeremyg-lunarg** [comment]
The first part is all that is desired, I think.  The OpenBSD maintainer ran into some obscure issues in VVL that were solved by c++17, and using the same standard across the ecosystem makes life simpler for everyone.
