### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment.

### ISSUE THREAD

**Issue by LIUQI-creat** [KhronosGroup/Vulkan-Tools#721]
Hi,
@nico @chewi @Zorro666 @olvaffe @jfroy 
I want to run **vulkaninfo** on a headless server, but I encountered some problems. The problems are fellows:
![image](https://user-images.githubusercontent.com/75316518/205652224-87050668-25c5-4ca4-94be-53d3cae8014d.png)

Then I set the DSIPLAY: (maybe it's wrong)
`export DISPLAY=:0.0`, then:
![image](https://user-images.githubusercontent.com/75316518/205652584-570a0550-c3ba-452f-a10b-a917bb09883c.png)

`error: XDG_RUNTIME_DIR not set in the environment.
XCB failed to connect to the X server due to error:1.`
How can I solve this problem? Thank you very mush!

**Comment by olvaffe** [comment]
vulkaninfo runs fine in an environment without `DISPLAY` and `XDG_RUNTIME_DIR`.  The errors about `XDG_RUNTIME_DIR` is from `libwayland-client.so`.

Since this is headless, I suppose there is no X nor Wayland servers running and you can ignore the error messages.  The issue seems to be that the vulkan loader cannot find the ICDs for nVidia GPUs.  Do you have the nVidia ICD installed?

If you want to debug this, you can `VK_LOADER_DEBUG=driver vulkaninfo > /dev/null` and see if the loader can find the nVidia ICD.  This is what things should be like when the loader find ICDs (intel, lvp, and radeon in this example)

```
DRIVER:           Searching for driver manifest files
DRIVER:              In following folders:
DRIVER:                 /home/olv/.config/vulkan/icd.d
DRIVER:                 /etc/xdg/vulkan/icd.d
DRIVER:                 /etc/vulkan/icd.d
DRIVER:                 /home/olv/.local/share/vulkan/icd.d
DRIVER:                 /usr/share/gnome/vulkan/icd.d
DRIVER:                 /usr/local/share/vulkan/icd.d
DRIVER:                 /usr/share/vulkan/icd.d
DRIVER:              Found the following files:
DRIVER:                 /usr/share/vulkan/icd.d/intel_icd.x86_64.json
DRIVER:                 /usr/share/vulkan/icd.d/lvp_icd.x86_64.json
DRIVER:                 /usr/share/vulkan/icd.d/radeon_icd.x86_64.json
```

**Comment by LIUQI-creat** [comment]
> 

When I run `VK_LOADER_DEBUG=driver vulkaninfo > /dev/null` , it still display:
```
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
XCB failed to connect to the X server due to error:1.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:612: failed with ERROR_INITIALIZATION_FAILED
```

Maybe I didn't install Vulkan properly? I have been troubled by it for a long time. (T＿T) 
What instructions should I execute to install Vulkan and vulkan tools? I don't have sudo permission, so I must execute them at the beginning of  making images.
Thank you very much!

**Comment by charles-lunarg** [comment]
> 1.2.131 Vulkan-Tools
That is a VERY old build of vulkaninfo. Could you try building a tip of `main` and try again?

The build instructions are pretty easy to follow if cmake & python is installed.
```
git clone https://github.com/KhronosGroup/Vulkan-Tools.git
cd Vulkan-Tools
mkdir build
cd build
python ../scripts/update_deps.py
cmake -C helper.cmake ..
cmake --build . 
(basically, just make sure you pass in helper.cmake when configuring CMake, then build like normal)
```

**Comment by charles-lunarg** [comment]
@LIUQI-creat pinging to see if there has been any updates since january.

**Comment by juan-lunarg** [comment]
closing due to lack of response / old version of sdk
