### ISSUE TITLE
vulkaninfo: optical flow queue flag is written with typo

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Tools#748]
optical flow flag is written `QUEUE_OPTICAL_FLOW_BIT_N` (wihtout a 'V' at the end)

```
	queueProperties[5]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 1
		queueFlags                  = QUEUE_TRANSFER | QUEUE_SPARSE_BINDING | QUEUE_OPTICAL_FLOW_BIT_N
		timestampValidBits          = 64
		present support             = false
```

as seen in https://github.com/KhronosGroup/Vulkan-Tools/blob/1a66f59f23ac2e45af4e38ee49c711df022a8f22/vulkaninfo/generated/vulkaninfo.hpp#L973

**Comment by charles-lunarg** [comment]
Ah, yes that definitely is wrong. 
Feel free to review the PR that fixes it, and thanks for reporting it!
