### ISSUE TITLE
BUILD.md needs updating

### ISSUE THREAD

**Issue by davidlunarg** [KhronosGroup/Vulkan-Tools#791]
README.md says to st PKG_CONFIG_LIBDIR as follows:

export PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu

But it also says: "Again, your PKG_CONFIG configuration may be different, depending on your
distribution."

To get 32-bit builds to work, I had to set use:

export PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig

Would be nice if this was documented rather than just indicating it may need to be different depending on distribution.

This was on Ubunutu 20.04.

**Comment by juan-lunarg** [comment]
I'll also address the initial issue but in reality the entire document is severely out of date.
