### ISSUE TITLE
vkcubepp leaks a command buffer and a command pool if iconized before stopping

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Tools#795]
From 1.3.250 SDK Testing:
Using SDK 1.3.250, Win 10, AMD, from powershell window run vkcubepp --validate.  Iconify the cubepp window and restore it.  Hit ESC to end the program and there are two popups complaining about a command buffer and a command pool that haven't been destroyed.
This doesn't happen with vkcube.  This doesn't happen if you don't iconify vkcubepp.

**Comment by charles-lunarg** [comment]
Does a command pool and command buffer get leaked for *each* time you iconify? Like if you did it 3 times, you'll get 3 leaks of each?

**Comment by Tony-LunarG** [comment]
Yes, it leaks one command buffer and command pool per iconify

**Comment by charles-lunarg** [comment]
That makes it pretty clear that the resize logic isn't cleaning up the objects then.
