### ISSUE TITLE
Mock ICD Warning

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Tools#798]
Occurs when I set `VK_LOADER_DEBUG` = `error,warn`

> WARNING: loader_add_layer_properties: Can not find 'layer' object in manifest JSON file D:\projects\vvl\build\install\bin\VkICD_mock_icd.json.  Skipping this file.

**Comment by charles-lunarg** [comment]
The issue is due to setting VK_LAYER_PATH to the same folder that the ICD is located in. The loader has to load all .json files but since its looking for layers, doesn't find the necessary details to load a layer when searching the mock_icd.json.
