### ISSUE TITLE
Vulkaninfo segfaults when VK_EXT_surface_maintenance1 is supported 

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-Tools#817]
vulkaninfo reports large amounts of validation errors then ultimately segfaults inside the driver when VK_EXT_surface_maintenance1 is supported.

Using vulkaninfo v 1.3.250 from the lunarg ubuntu 22.04 packages.

Full output from vkconfig: https://gist.github.com/HildarTheDorf/4755c7bcc7b18b9aff66c2f1868bac88

Backtrace:
```
==106517== Process terminating with default action of signal 11 (SIGSEGV)
==106517==  Access not within mapped region at address 0x296170702D
==106517==    at 0x11F63224: vk_get_physical_device_core_1_1_property_ext (vk_device.c:838)
==106517==    by 0x1209FBCA: lvp_GetPhysicalDeviceProperties2 (lvp_device.c:1075)
==106517==    by 0x145F5A77: vulkan_layer_chassis::GetPhysicalDeviceProperties2KHR(VkPhysicalDevice_T*, VkPhysicalDeviceProperties2*) (chassis.cpp:6631)
==106517==    by 0x1248DE: AppGpu::AppGpu(AppInstance&, unsigned int, VkPhysicalDevice_T*) (vulkaninfo.h:1552)
==106517==    by 0x11E1F0: main (vulkaninfo.cpp:1111)
```

**Comment by charles-lunarg** [comment]
This is very likely solved by vulkaninfo not enabling all extensions #799 but since I don't have a system which supports the extension, I can't confirm if its fixed or not.

**Comment by charles-lunarg** [comment]
Was able to build mesa and run vulkaninfo (from packages and main), showing that the validation errors went away, which presumably means the crash also will not occur. If it still does after the next SDK release, feel free to reopen.
