### ISSUE TITLE
actions: MoltenVK caching doesn't appear to be working

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-Tools#820]
Recent github actions run took ~35 minutes to run the configure step in the mac job.

https://github.com/KhronosGroup/Vulkan-Tools/actions/runs/5318514414/jobs/9630061570
```
 Checking out MoltenVK in /Users/runner/work/Vulkan-Tools/Vulkan-Tools/external/Release/MoltenVK
Cloning MoltenVK into /Users/runner/work/Vulkan-Tools/Vulkan-Tools/external/Release/MoltenVK
b'HEAD detached at v1.2.4\nnothing to commit, working tree clean\n'
Building MoltenVK in /Users/runner/work/Vulkan-Tools/Vulkan-Tools/external/Release/MoltenVK
Build dir = /Users/runner/work/Vulkan-Tools/Vulkan-Tools/external/Release/MoltenVK
Install dir = /Users/runner/work/Vulkan-Tools/Vulkan-Tools/external/Release/MoltenVK
```

I hazard a guess that ccache isn't capturing MoltenVK properly, and thus its rebuilding it (which takes forever) every CI job.

**Comment by juan-lunarg** [comment]
Looks fine to me:
https://github.com/KhronosGroup/Vulkan-Tools/actions/runs/5325012754/jobs/9645131031?pr=821

Dunno what happened.
