### ISSUE TITLE
VkSurfacePresentModeCompatibilityEXT passed without VkSurfacePresentModeEXT

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/Vulkan-Tools#846]
> If a [VkSurfacePresentScalingCapabilitiesEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfacePresentScalingCapabilitiesEXT.html) structure is included in the pNext chain of pSurfaceCapabilities, a [VkSurfacePresentModeEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfacePresentModeEXT.html) structure must be included in the pNext chain of pSurfaceInfo
>
> — https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfaceCapabilities2KHR.html#VUID-vkGetPhysicalDeviceSurfaceCapabilities2KHR-pNext-07776

However, vulkaninfo passes `VkSurfacePresentModeCompatibilityEXT` without a `VkSurfacePresentModeEXT` chained up.

This makes Mesa crash.

**Comment by charles-lunarg** [comment]
So looking at this VUID, its clear that I need to supply a `VkPresentModeKHR` for the VUID to be satisfied (through `VkSurfacePresentModeEXT`). The hangup is "which" mode to use. Because now I think its necessary to call the function multiple times, one for each present mode, and print the surface_maintenance1 capabilities for each present mode. Does that seem reasonable?

**Comment by emersion** [comment]
Yeah, I think it would make sense to query the present mode compatibility for each present mode supported by the Vulkan implementation.

**Comment by charles-lunarg** [comment]
I started to work on this issue but got distracted by other repo's (loader & vulkan-utility-library).

I hope to have a fix for this up by the end of the week, its not great to be shipping vulkaninfo with such a bug in it.

**Comment by charles-lunarg** [comment]
@emersion I added sample output in the PR I just linked. This is what it'll look like in the text output of vulkaninfo. Let me know if it makes sense or needs tweaking.

**Comment by emersion** [comment]
Yes, that makes sense to me. Thanks!
