### ISSUE TITLE
Remove ndk-build

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Tools#850]
Use CMake for Android builds

Currently the Android build only builds `vulkaninfo` and `vkcube`

```
[armeabi-v7a] Install        : vulkaninfo => libs/armeabi-v7a/vulkaninfo
[arm64-v8a] Install        : vulkaninfo => libs/arm64-v8a/vulkaninfo
[x86] Install        : vulkaninfo => libs/x86/vulkaninfo
[x86_64] Compile++      : vulkaninfo <= vulkaninfo.cpp
[x86_64] Executable     : vulkaninfo
[x86_64] Install        : vulkaninfo => libs/x86_64/vulkaninfo
```

```
[armeabi-v7a] Install        : libVkCube.so => libs/armeabi-v7a/libVkCube.so
[arm64-v8a] Install        : libVkCube.so => libs/arm64-v8a/libVkCube.so
[x86] Install        : libVkCube.so => libs/x86/libVkCube.so
[x86_64] Install        : libVkCube.so => libs/x86_64/libVkCube.so
```

This is the last repository that still has `ndk-build` support.

**Comment by juan-lunarg** [comment]
@charles-lunarg does vulkaninfo actually work on Android? It's curious because it looks like an actual executable.

IE do I need to get vulkaninfo working on Android?

**Comment by charles-lunarg** [comment]
So vulkaninfo has code inside of it for android, but I do think we maintain it at all. `vkinfo` is the current way to get info about vulkan on android, and while vulkaninfo might support android officially in the future, it is currently not.

So no, I wouldn't take time to make it work.

**Comment by charles-lunarg** [comment]
So I can confirm (thanks to @mikes-lunarg) that Vulkaninfo works on android in the sense that it doesn't need modification to compile and run. That said, it still needs a bit of finagling to build it, using the bash script below.

There was one code modification needed, which is to remove the `if (ANDROID) return() endif()` in CMake. 

This build script also turns X11, XCB, and Wayland off completely, which indicates that those build options should auto turn off when building in android. 

```bash
git clone https://github.com/KhronosGroup/Vulkan-Tools
cd Vulkan-Tools
python3 scripts/update_deps.py --dir=external

cmake -S . -B android-build -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=28 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DBUILD_CUBE=OFF -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF -C external/helper.cmake
cmake --build android-build --target vulkaninfo

adb push android-build/vulkaninfo/vulkaninfo /data/local/tmp
adb shell /data/local/tmp/vulkaninfo --json --output /data/local/tmp/VP_Pixel_6.json
adb pull /data/local/tmp/VP_Pixel_6.json
```

**Comment by juan-lunarg** [comment]
👍🏾
