### ISSUE TITLE
icd/CMakeLists.txt should not use copy command when targeting WIN32

### ISSUE THREAD

**Issue by water-chika** [KhronosGroup/Vulkan-Tools#861]
In icd/CMakeLists.txt, there are statements like:
```
if (WIN32)
  add_custom_target(json COMMAND copy src_json dst_json)
endif()
```

In CMake code, the ```CMAKE_SYSTEM_XXX``` variables always describe the target platform. The same is true for the short ```WIN32```, ```UNIX```, ```APPLE``` variables. (https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html)
WIN32 do not mean host platform is Windows rather than means target platform is Windows. 
And copy command is a windows command. It should only be used on Windows platform. It should be used like:
```
if (CMAKE_HOST_WIN32)
  add_custom_target(json COMMAND copy src_json dst_json)
endif()
```

I think origin statements could be changed to:
```
if (WIN32)
  configure_file(src_json dst_json COPYONLY)
  add_custom_target(json DEPENDS dst_json)
endif()
```

**Comment by juan-lunarg** [comment]
I'm updating the JSON logic to be similar to the logic in the validation layers since it's essentially the same thing.
