### ISSUE TITLE
ANGLE rolls breaking on Windows after ICD json change

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/Vulkan-Tools#866]
Hello,
After the change regarding the ICD json logic update (9616098f617c4a53ecb72a1456bb229989e2d0e4), we see that ANGLE rolls fail on some tests on Windows with the following error:
```
RendererVk.cpp:191 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
RendererVk.cpp:191 (VerifyExtensionsPresent): Extension not supported: VK_KHR_win32_surface
Display.cpp:1052 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ..\..\src\libANGLE\renderer\vulkan\RendererVk.cpp, enableInstanceExtensions:1698.
```
The output JSON file (`VkICD_mock_icd.json`) has been changed to include the following:
```
"library_path": "..\\VkICD_mock_icd.dll",
```
If the line above is changed to `.\\VkICD_mock_icd.dll`, the failing tests from above pass.

CC: @juan-lunarg

**Comment by juan-lunarg** [comment]
I have a PR up which should address this.

**Comment by aabdolrashidi** [comment]
Thank you! The issue has been fixed.
