### ISSUE TITLE
The cube directory should be renamed to vkcube

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Tools#90]
PR #88 renames cube to vkcube, and cubepp to vkcubepp, but because the spec points to the cube source code, changing the directory name or source file name would break the link in the spec.  The directory name should be changed to vkcube and should be coordinated with changing the link in the spec

**Comment by KarenGhavam-lunarG** [comment]
This has been open for over a year. I realize that the spec refers to "cube" and our SDK builds the source cube.c to create a vkcube executable. Although it might be prettier to use the word vkcube.c in the specification, I am not sure it is worth the effort to make this change. Making the change will probably break "many things in many places" that we can't imagine.

I am going to close this. If you disagree, let me know.
