### ISSUE TITLE
Error building with cmake

### ISSUE THREAD

**Issue by AlphaCog** [KhronosGroup/Vulkan-Tools#947]
username@Gallium:~/Vulkan-Tools$ cmake -S . -B build -D UPDATE_DEPS=ON -D BUILD_WERROR=ON -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Debug
CMake Error: The source directory "/home/username/Vulkan-Tools/CMAKE_BUILD_TYPE=Debug" does not exist.

**Comment by charles-lunarg** [comment]
This is more of a CMake issue rather than one with our repository. I ran the exact command you gave here and did not have any issues. Can you remove the Vulkan-Tools directory entirely and retry?

**Comment by juan-lunarg** [comment]
Try the following:

```
rm -rf build

cmake -S . -B build -DUPDATE_DEPS=ON -DCMAKE_BUILD_TYPE=Debug
```

**Comment by juan-lunarg** [comment]
Closing due to lack of response.

Feel free to check our CI we build CMake regularly. It's likely user error. Make sure you are also using at least CMake 3.17
