### ISSUE TITLE
Make vulkaninfo removal of promoted extension structures optional

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-Tools#963]
PR  #948  removed extension structures from vulkaninfo output that were promoted to core Vulkan, eg into the VkPhysicalDeviceVulkan(11|12|13)(Features|Properties) structs. It was done for Vulkan profile generation, but it users who are looking for the extension structures explicitly as they no longer appear.

PR 948 was a necessary contribution to allow correct Vulkan-Profile output, but should be a command line option, eg ~~`--remove-promoted-extensions`~~ `--strip_duplicate_struct`.

**Comment by christophe-lunarg** [comment]
In the Vulkan Profiles merge script, the argument is called `--strip_duplicate_struct` if we want to be consistant. If you prefer a different name, I'll happy to use that name.

**Comment by charles-lunarg** [comment]
`--strip_duplicate_struct` is a much better name, because 'strip' better describes whats happening.

**Comment by rumblehhh** [comment]
Jumping on this to add that we were recently bitten by this. We use vulkaninfo's json option for checking implementation features/properties to avoid running unsupported tests/content.
After upgrading to a version of vulkaninfo after https://github.com/KhronosGroup/Vulkan-Tools/pull/948 a number of our tests were being unexpectedly skipped. For now we've had to downgrade to workaround the missing structures.

**Comment by charles-lunarg** [comment]
@rumblehhh I pushed up a new option to vulkaninfo `show-all-structs`. Could you try out the branch? And also very open to bikeshedding the name of the option. In my head, this option 'shows all structs' that would previously be hidden. But I'm open to suggestions.

**Comment by rumblehhh** [comment]
@charles-lunarg thanks for the changes! I've checked out the branch and I believe this should work fine for us.
Should this, or another option if the name changes, actually show all structures including alias structures?

Taking the `dynamicRendering` feature as an example
- `main` shows `VkPhysicalDeviceVulkan13Features`
- `--show-all-structs` shows `VkPhysicalDeviceVulkan13Features` and `VkPhysicalDeviceDynamicRenderingFeatures`

`--show-all-structs` implies vulkaninfo should be showing *all* structures which you may think should additionally include `VkPhysicalDeviceDynamicRenderingFeaturesKHR`.

As for other names:
--`hide-promoted-structs`
--`show-promoted-structs`
and depending on the above you may also want `show-alias-structs` or `hide-alias-structs`

**Comment by JamesRumble-IMG** [comment]
@charles-lunarg are there any updates on this?

**Comment by charles-lunarg** [comment]
@rumblehhh I took your advice and changed it to `--show-promoted-structs. "all" implies things that are above and beyond what are actually being done. 

@JamesRumble-IMG Thank you for the reminder - this PR was low priority and thus fell off my todo list. It was a simple rebase and name change to get this ready to ship. (I also found a bug in my code, so that was good).

**Comment by JamesRumble-IMG** [comment]
Thanks very much for adding the `--show-promoted-structs` feature!
