### ISSUE TITLE
vulkaninfo: Ignoring VkPhysicalDeviceHostImageCopyPropertiesEXT for Vulkan Profile output

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Tools#973]
In the Vulkan Profiles tools and vulkancapsviewer we made the call to ignore/disacard VkPhysicalDeviceHostImageCopyPropertiesEXT because it's definision causes issues. It's the only vkGetProperties struct that requires two passes to get the data. However, applications may chain the structs make the calls and have not way to deal with the intermediate results.

So currently vulkaninfo generate Vulkan Profiles that are invalid because it output VkPhysicalDeviceHostImageCopyPropertiesEXT. Could vulkaninfo skip this structure explicitly?

**Comment by charles-lunarg** [comment]
@christophe-lunarg PR is up, would appreciate a review so it can be merged.
